import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("the 3D world consumes one shared Kai expression without recoloring authored environments", async () => {
  const canvas = await readFile("src/features/play/WildsWorldCanvas.tsx", "utf8");
  const actor = await readFile("src/features/play/WildsCreatureActor.tsx", "utf8");
  const atmosphere = await readFile("src/features/play/WildsAtmosphere.tsx", "utf8");
  const geometry = await readFile("src/features/play/WildsKaiAtmosphereGeometry.tsx", "utf8");
  assert.match(canvas, /projectKaiWorldExpression/);
  assert.match(canvas, /<WildsAtmosphere[\s\S]*expression=\{kaiExpression\}/);
  assert.match(canvas, /<WildsKaiAtmosphereGeometry/);
  assert.match(canvas, /projectCardKaiAppearance/);
  assert.match(canvas, /appearance\.palette\.primary/);
  assert.match(canvas, /appearance\.palette\.secondary/);
  assert.match(canvas, /appearance\.palette\.accent/);
  assert.match(canvas, /appearance\.palette\.glow/);
  assert.match(canvas, /appearance\.morphology/);
  assert.match(atmosphere, /KaiWorldExpression/);
  assert.match(atmosphere, /expression\.sun/);
  assert.match(atmosphere, /expression\.lighting/);
  assert.match(geometry, /Math\.min\(16/);
  assert.doesNotMatch(geometry, /useFrame\([\s\S]{0,300}set[A-Z]/);
  assert.doesNotMatch(canvas, /world\.chapter\.palette\.(?:ground|mid|accent)[\s\S]{0,80}kaiExpression/);
  assert.match(actor, /const bodyColorFloor = pose === "capture" \? 0\.2 : 0\.11/);
  assert.match(actor, /Math\.max\(bodyColorFloor, readability\.actorEmissive\)/);
  assert.match(actor, /emissiveIntensity=\{readableBodyColorFloor\}/);
  assert.match(actor, /const renderedAccent = threeCreatureColor\(accent\)/);
  assert.match(actor, /const renderedSecondary = threeCreatureColor\(secondary\)/);
  assert.match(actor, /const renderedGlow = threeCreatureColor\(glow\)/);
  assert.match(actor, /emissive=\{renderedPrimary\} emissiveIntensity=\{0\.07 \+ readability\.actorEmissive \* 0\.45\}/);
  assert.match(actor, /body === "winged"[\s\S]{0,500}color=\{renderedSecondary\}/);
  assert.match(actor, /color=\{renderedGlow\} emissive=\{renderedGlow\} emissiveIntensity=\{0\.52\}/);
});
