import assert from 'node:assert/strict';
import { test } from 'node:test';
import { planCreation } from '../src/features/play/creation/planner';
import { creationDefinitionFixture,creationContextFixture } from './support/creation-fixtures';
const request=()=>({requestId:'request',actorId:'owner',message:'Build a room with an open door',selected:creationDefinitionFixture(),workers:[{assetId:'card',subjectId:'creature',head:`sha256:${'a'.repeat(64)}`,proofDigest:`sha256:${'b'.repeat(64)}`,techniques:['assembly'],ready:true,reasons:[]}],context:creationContextFixture()});
test('preserves a draft when generation is unavailable',async()=>{const input=request(),before=structuredClone(input.selected);const result=await planCreation(input,{propose:async()=>{throw Error('offline');}},new AbortController().signal);assert.equal(result.status,'unavailable');assert.deepEqual(input.selected,before);});
test('validates generated graph identity and stale replies',async()=>{const input=request();const good={requestId:input.requestId,reply:'A timber room with a doorway.',definition:input.selected};assert.equal((await planCreation(input,{propose:async()=>good},new AbortController().signal)).status,'proposed');for(const output of ['{partial', {...good,requestId:'old'},{...good,definition:{...input.selected,creatorId:'other'}},{...good,definition:{...input.selected,nodes:[{...input.selected.nodes[0],behaviors:[{id:'infinite-money',version:1,parameters:{}}]}]}}])assert.equal((await planCreation(input,{propose:async()=>output},new AbortController().signal)).status,'blocked');});
test('binds patches to selected object and aborts a hung provider',async()=>{const input=request();const stale={requestId:'request',reply:'Edit',patch:{baseDigest:'old',operations:[]}};assert.equal((await planCreation(input,{propose:async()=>stale},new AbortController().signal)).status,'blocked');const abort=new AbortController();const pending=planCreation(input,{propose:async()=>new Promise(()=>{})},abort.signal);abort.abort();assert.equal((await pending).status,'unavailable');});
test('rejects invalid budget before asking provider',async()=>{let calls=0;const input=request();const result=await planCreation({...input,context:{...input.context,budget:{timber:-1}}},{propose:async()=>{calls++;return {}; }},new AbortController().signal);assert.equal(result.status,'blocked');assert.equal(calls,0);});
