import assert from 'node:assert/strict';
import { test } from 'node:test';
import { creationOperationContextFixture } from './support/creation-operation-fixtures';
import { createCreationController } from '../src/features/play/creation/controller';
import { compileCreation } from '../src/features/play/creation/compiler';
import { prepareCreationOperation, createCreationAdmissionPort, type CreationOperation } from '../src/features/play/creation/operation';
import { planCreationTasks, prepareCreationCrewBatch } from '../src/features/play/creation/crew';
import { createCreationCrewJournal } from '../src/features/play/creation/crew-journal';
import { createMemoryWildzContinuityDatabase } from './support/memory-wildz-continuity-database';
import { projectCreationPhysical } from '../src/features/play/creation/projection';
function outcome(op: CreationOperation) { const h = `sha256:${'c'.repeat(64)}`; return { status: 'admitted' as const, operationId: op.operationId, operationDigest: op.digest, instance: op.command.instance, successorSources: [{ id: op.instanceId, head: op.command.instance.head, kind: 'creation', parentHead: null }, ...op.command.resourceSuccessors.map(r => ({ id: r.id, head: r.head, kind: r.kind, parentHead: op.expectedHeads[r.id] })), ...op.workerAllocations.filter(w => w.work > 0).map(w => ({ id: w.workerId, head: h, kind: 'creature', parentHead: op.expectedHeads[w.workerId] })), { id: `space:${op.command.instance.spaceId}`, head: h, kind: 'space', parentHead: op.expectedHeads[`space:${op.command.instance.spaceId}`] }], eventIds: ['test:event'], receipt: 'test-only-controller-source' }; }
async function fixture() { const context = creationOperationContextFixture(), compiled = compileCreation(context.definition, context.compileContext); if (compiled.status !== 'ready')
    throw Error('fixture'); const operation = prepareCreationOperation(compiled.plan, context), worker = context.workers[0].subjectId, evidence = { ownerHead: operation.expectedHeads['actor:owner']!, workerHeads: { [worker]: context.workers[0].head }, jobHeads: { [worker]: `sha256:${'b'.repeat(64)}` }, readyWorkerIds: [worker], consentingWorkerIds: [worker], arrivedWorkerIds: [worker], revokedWorkerIds: [] }, batch = await prepareCreationCrewBatch(planCreationTasks(compiled.plan, context.workers), { batchId: 'controller:batch', operation, evidence, readEvidence: async () => evidence }), journal = createCreationCrewJournal('owner', createMemoryWildzContinuityDatabase()); await journal.observeEvidence(null, evidence); return { context, plan: compiled.plan, operation, batch, journal, evidence }; }
test('controller exposes usable physical state only after authenticated crew admission and projection', async () => { const f = await fixture(); let writes = 0; const controller = createCreationController({ environment: () => ({ ownerId: 'owner', worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => f.batch, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: fence => createCreationAdmissionPort({ operationForLookup: async (id) => (await f.journal.read(id))?.operation ?? null, executeRaw: async (op) => { assert.equal(await fence(), true); writes++; return outcome(op); }, lookupRaw: async () => outcome(f.operation), authenticate: async (_op, r) => (r as {
            receipt?: string;
        }).receipt === 'test-only-controller-source' }) }); assert.equal(controller.snapshot().projections.length, 0); const result = await controller.commit(f.context.definition, f.plan, ['fixture:card']); assert.equal(result.status, 'admitted'); assert.equal(writes, 1); assert.equal(controller.snapshot().projections.length, 1); assert.equal(controller.snapshot().navigation.instanceCount, 1); const recovered = await controller.recover(f.batch.batchId, f.plan); assert.equal(recovered.status, 'admitted'); assert.equal(writes, 1); });
test('changed owner during preparation cannot dispatch or put old-owner state into the scene', async () => { const f = await fixture(); let ownerId = 'owner', writes = 0; const controller = createCreationController({ environment: () => ({ ownerId, worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => { ownerId = 'recipient'; return f.batch; }, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: () => ({ execute: async (op) => { writes++; return { status: 'unknown', operationId: op.operationId }; }, lookup: async (id) => ({ status: 'unknown', operationId: id }) }) }); assert.equal((await controller.commit(f.context.definition, f.plan, ['fixture:card'])).status, 'rejected'); assert.equal(writes, 0); assert.equal(controller.snapshot().projections.length, 0); });
test('owner changes during authorization prevent dispatch', async () => { const f = await fixture(); let ownerId = 'owner', writes = 0; const controller = createCreationController({ environment: () => ({ ownerId, worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => { ownerId = 'recipient'; return f.evidence; }, prepare: async () => f.batch, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: () => ({ execute: async (op) => { writes++; return { status: 'unknown', operationId: op.operationId }; }, lookup: async (id) => ({ status: 'unknown', operationId: id }) }) }); await controller.commit(f.context.definition, f.plan, ['fixture:card']); assert.equal(writes, 0); assert.equal(controller.snapshot().projections.length, 0); });
test('editing a selected admitted instance cannot silently build a new copy', async () => { const f = await fixture(); let writes = 0; const controller = createCreationController({ environment: () => ({ ownerId: 'owner', worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => f.batch, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: () => ({ execute: async (op) => { writes++; return { status: 'unknown', operationId: op.operationId }; }, lookup: async (id) => ({ status: 'unknown', operationId: id }) }) }); const selected = { instanceId: 'existing', head: f.operation.command.instance.head, definitionDigest: f.context.definition.digest }; const result = await controller.commit(f.context.definition, f.plan, ['fixture:card'], selected); assert.equal(result.status, 'rejected'); assert.equal(writes, 0); });
