import assert from 'node:assert/strict';
import { test } from 'node:test';
import { sealConstructionProof } from '../src/features/play/wilds-construction-project';
import { selectCreationResources } from '../src/features/play/creation/resources';
const lot=sealConstructionProof({schema:'wildz.material-lot.v1' as const,lotId:`wildz:material:timber:${'1'.repeat(64)}`,kind:'timber' as const,quantity:1 as const,quality:1 as const,ownerReceizId:'owner',source:{sourceId:'tree',sourceHead:`sha256:${'a'.repeat(64)}`,admittedSourceHead:`sha256:${'b'.repeat(64)}`,kaiUPulse:1},contributors:{explorerReceizId:'owner'},authority:'source-proof-object' as const});
const available={actorId:'owner',heads:{[lot.lotId]:lot.head},custody:{[lot.lotId]:'owner'},reserved:new Set<string>(),spent:new Set<string>(),stored:new Set<string>()};
test('rejects a previously consumed resource lot',()=>{const selection=selectCreationResources([lot],{timber:1},{timber:1},{...available,spent:new Set([lot.lotId])});assert.equal(selection.lots.length,0);assert.ok(selection.deficits.timber>0);});
test('selects exact current custody once without changing it',()=>{const before=structuredClone(lot);const r=selectCreationResources([lot,lot],{timber:2},{timber:2},available);assert.equal(r.lots.length,1);assert.equal(r.deficits.timber,1);assert.deepEqual(lot,before);for(const reason of ['reserved','stored'] as const)assert.equal(selectCreationResources([lot],{timber:1},{timber:1},{...available,[reason]:new Set([lot.lotId])}).lots.length,0);assert.equal(selectCreationResources([lot],{timber:1},{timber:1},{...available,heads:{}}).lots.length,0);});
test('validates budget ceilings and denies forged resource quantities',()=>{assert.throws(()=>selectCreationResources([lot],{timber:-1},{timber:1},available));assert.equal(selectCreationResources([lot],{timber:0},{timber:1},available).lots.length,0);assert.equal(selectCreationResources([{...lot,quantity:999} as never],{timber:999},{timber:999},available).lots.length,0);});
