import assert from 'node:assert/strict';
import { test } from 'node:test';
import { sealConstructionProof } from '../src/features/play/wilds-construction-project';
import { extractCreationResource } from '../src/features/play/creation/resource-source';
import { sealCreationResourceLot, verifyCreationResourceLot, CREATION_RESOURCE_RULE_HEAD } from '../src/features/play/creation/resource-registry';
import type { CreationAuthorityContext } from '../src/features/play/creation/state';
import { creationSourceHead } from './support/creation-instance-fixtures';
function fixture() { const source = sealConstructionProof({ schema: 'wildz.creation-finite-resource-source.v1' as const, id: 'seeds', parentHead: null, kind: 'seed' as const, worldId: 'wildz', spaceId: 'surface', capacity: 16, remaining: 16, kaiUPulse: 1 }), sources = [{ id: source.id, head: source.head, kind: 'resource-source' }, { id: 'rule:creation.resources.v1', head: CREATION_RESOURCE_RULE_HEAD, kind: 'rule' }, { id: 'actor:owner', head: creationSourceHead, kind: 'actor' }], authority: CreationAuthorityContext = { actorId: 'owner', sources, rules: { 'creation.resources.v1': CREATION_RESOURCE_RULE_HEAD }, verifySource: s => sources.some(x => x.id === s.id && x.head === s.head && x.kind === s.kind), mandates: [] }; return { source, authority, input: { operationId: 'extract:1', actorId: 'owner', expectedHead: source.head, quantity: 16, lotId: 'lot:seeds', kaiUPulse: 2 } }; }
test('finite extraction debits the exact source and binds a lot to its consumed head', () => { const f = fixture(), next = extractCreationResource(f.source, f.input, f.authority); assert.equal(next.source.remaining, 0); assert.equal(next.lot.quantity, 16); assert.equal(next.lot.sourceHead, f.source.head); assert.equal(verifyCreationResourceLot(next.lot), true); assert.throws(() => extractCreationResource(next.source, { ...f.input, expectedHead: next.source.head, quantity: 1 }, f.authority)); assert.throws(() => extractCreationResource(f.source, { ...f.input, quantity: 17 }, f.authority)); assert.throws(() => extractCreationResource(f.source, f.input, { ...f.authority, verifySource: () => false })); });
test('resource laws reject hidden extra statistics even with a correct structural seal', () => { const f = fixture(), r = extractCreationResource(f.source, f.input, f.authority), { head, ...lot } = r.lot; void head; assert.throws(() => sealCreationResourceLot({ ...lot, infinite: true } as typeof lot)); const { head: old, ...basis } = f.source; void old; const altered = sealConstructionProof({ ...basis, infinite: true }), authority = { ...f.authority, sources: [...f.authority.sources.filter(s => s.id !== f.source.id), { id: altered.id, head: altered.head, kind: 'resource-source' }], verifySource: () => true }; assert.throws(() => extractCreationResource(altered, { ...f.input, expectedHead: altered.head }, authority)); });
