import assert from 'node:assert/strict';
import { test } from 'node:test';
import { creationOperationContextFixture } from './support/creation-operation-fixtures';
import { createCreationController } from '../src/features/play/creation/controller';
import { compileCreation } from '../src/features/play/creation/compiler';
import { prepareCreationOperation, createCreationAdmissionPort, type CreationOperation } from '../src/features/play/creation/operation';
import { planCreationTasks, prepareCreationCrewBatch } from '../src/features/play/creation/crew';
import { createCreationCrewJournal } from '../src/features/play/creation/crew-journal';
import { createMemoryWildzContinuityDatabase } from './support/memory-wildz-continuity-database';
import { projectCreationPhysical } from '../src/features/play/creation/projection';
import {createCreationDefinition} from '../src/features/play/creation/definition';
import {sealCreationInstance} from '../src/features/play/creation/instance';
import {initializeCreationComponents} from '../src/features/play/creation/components';
import { createCreationCurrentSourcePort } from '../src/features/play/creation/current-source';
function outcome(op: CreationOperation) { const h = `sha256:${'c'.repeat(64)}`; return { status: 'admitted' as const, operationId: op.operationId, operationDigest: op.digest, instance: op.command.instance, successorSources: [{ id: op.instanceId, head: op.command.instance.head, kind: 'creation', parentHead: null }, ...op.command.resourceSuccessors.map(r => ({ id: r.id, head: r.head, kind: r.kind, parentHead: op.expectedHeads[r.id] })), ...op.workerAllocations.filter(w => w.work > 0).map(w => ({ id: w.workerId, head: h, kind: 'creature', parentHead: op.expectedHeads[w.workerId] })), { id: `space:${op.command.instance.spaceId}`, head: h, kind: 'space', parentHead: op.expectedHeads[`space:${op.command.instance.spaceId}`] }], eventIds: ['test:event'], receipt: 'test-only-controller-source' }; }
async function fixture() { const context = creationOperationContextFixture(), compiled = compileCreation(context.definition, context.compileContext); if (compiled.status !== 'ready')
    throw Error('fixture'); const operation = prepareCreationOperation(compiled.plan, context), worker = context.workers[0].subjectId, evidence = { ownerHead: operation.expectedHeads['actor:owner']!, workerHeads: { [worker]: context.workers[0].head }, jobHeads: { [worker]: `sha256:${'b'.repeat(64)}` }, readyWorkerIds: [worker], consentingWorkerIds: [worker], arrivedWorkerIds: [worker], revokedWorkerIds: [] }, batch = await prepareCreationCrewBatch(planCreationTasks(compiled.plan, context.workers), { batchId: 'controller:batch', operation, evidence, readEvidence: async () => evidence }), journal = createCreationCrewJournal('owner', createMemoryWildzContinuityDatabase()); await journal.observeEvidence(null, evidence); return { context, plan: compiled.plan, operation, batch, journal, evidence }; }
test('controller exposes usable physical state only after authenticated crew admission and projection', async () => { const f = await fixture(); let writes = 0; const controller = createCreationController({ environment: () => ({ ownerId: 'owner', worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => f.batch, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: fence => createCreationAdmissionPort({ operationForLookup: async (id) => (await f.journal.read(id))?.operation ?? null, executeRaw: async (op) => { assert.equal(await fence(), true); writes++; return outcome(op); }, lookupRaw: async () => outcome(f.operation), authenticate: async (_op, r) => (r as {
            receipt?: string;
        }).receipt === 'test-only-controller-source' }) }); assert.equal(controller.snapshot().projections.length, 0); const result = await controller.commit(f.context.definition, f.plan, ['fixture:card']); assert.equal(result.status, 'admitted'); assert.equal(writes, 1); assert.equal(controller.snapshot().projections.length, 1); assert.equal(controller.snapshot().navigation.instanceCount, 1); const recovered = await controller.recover(f.batch.batchId, f.plan); assert.equal(recovered.status, 'admitted'); assert.equal(writes, 1); });
test('changed owner during preparation cannot dispatch or put old-owner state into the scene', async () => { const f = await fixture(); let ownerId = 'owner', writes = 0; const controller = createCreationController({ environment: () => ({ ownerId, worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => { ownerId = 'recipient'; return f.batch; }, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: () => ({ execute: async (op) => { writes++; return { status: 'unknown', operationId: op.operationId }; }, lookup: async (id) => ({ status: 'unknown', operationId: id }) }) }); assert.equal((await controller.commit(f.context.definition, f.plan, ['fixture:card'])).status, 'rejected'); assert.equal(writes, 0); assert.equal(controller.snapshot().projections.length, 0); });
test('owner changes during authorization prevent dispatch', async () => { const f = await fixture(); let ownerId = 'owner', writes = 0; const controller = createCreationController({ environment: () => ({ ownerId, worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => { ownerId = 'recipient'; return f.evidence; }, prepare: async () => f.batch, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: () => ({ execute: async (op) => { writes++; return { status: 'unknown', operationId: op.operationId }; }, lookup: async (id) => ({ status: 'unknown', operationId: id }) }) }); await controller.commit(f.context.definition, f.plan, ['fixture:card']); assert.equal(writes, 0); assert.equal(controller.snapshot().projections.length, 0); });
test('editing a selected admitted instance cannot silently build a new copy', async () => { const f = await fixture(); let writes = 0; const controller = createCreationController({ environment: () => ({ ownerId: 'owner', worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => f.batch, project: async (i, d, p) => projectCreationPhysical(i, d, p), createAdmission: () => ({ execute: async (op) => { writes++; return { status: 'unknown', operationId: op.operationId }; }, lookup: async (id) => ({ status: 'unknown', operationId: id }) }) }); const selected = { instanceId: 'existing', head: f.operation.command.instance.head, definitionDigest: f.context.definition.digest }; const result = await controller.commit(f.context.definition, f.plan, ['fixture:card'], selected); assert.equal(result.status, 'rejected'); assert.equal(writes, 0); });

test('owner change while worker projection awaits cannot publish old account geometry', async () => {
  const f = await fixture(); let ownerId = 'owner';
  const controller = createCreationController({ environment: () => ({ ownerId, worldId: f.plan.worldId, spaceId: f.plan.spaceId }), journal: f.journal, authorize: async () => f.evidence, prepare: async () => f.batch,
    project: async (i,d,p) => { ownerId = 'recipient'; return projectCreationPhysical(i,d,p); },
    createAdmission: fence => createCreationAdmissionPort({ operationForLookup: async id => (await f.journal.read(id))?.operation ?? null, executeRaw: async op => { assert.equal(await fence(),true); return outcome(op); }, lookupRaw: async () => outcome(f.operation), authenticate: async (_op,r) => (r as { receipt?: string }).receipt === 'test-only-controller-source' }) });
  assert.equal((await controller.commit(f.context.definition,f.plan,['fixture:card'])).status,'unknown');
  assert.equal(controller.snapshot().projections.length,0);
});

test('controller restores a current source without re-dispatching its historical construction', async () => {
  const f=await fixture(); let dispatches=0;
  const currentSources=createCreationCurrentSourcePort({read:async()=>({status:'available',instance:f.operation.command.instance,definition:f.context.definition,planDigest:f.plan.digest,source:'test-only-current-source'}),authenticateCurrent:async r=>r.source==='test-only-current-source'});
  const controller=createCreationController({environment:()=>({ownerId:'owner',worldId:f.plan.worldId,spaceId:f.plan.spaceId}),journal:f.journal,authorize:async()=>f.evidence,prepare:async()=>f.batch,currentSources,project:async(i,d,p)=>projectCreationPhysical(i,d,p),createAdmission:()=>({execute:async op=>{dispatches++;return {status:'unknown',operationId:op.operationId};},lookup:async id=>({status:'unknown',operationId:id})})});
  assert.equal(await controller.hydrate(f.operation.instanceId,f.plan),true);
  assert.equal(dispatches,0); assert.equal(controller.snapshot().projections.length,1);
});

async function evolutionFixture(){
 const f=await fixture(),{digest,...basis}=f.context.definition,definition=createCreationDefinition({...basis,nodes:[...basis.nodes,{...basis.nodes[0],id:'bench',pose:{position:{x:8,y:0,z:0},yaw:0},shape:{kind:'box',width:1,height:.2,depth:1}}]}),selected={instanceId:f.operation.instanceId,head:f.operation.command.instance.head,definitionDigest:f.context.definition.digest};
 const compiled=compileCreation(definition,{...f.context.compileContext,budget:{timber:1},evolution:{instanceId:selected.instanceId,head:selected.head,definition:f.context.definition}});if(compiled.status!=='ready')throw Error('evolution fixture');
 const {head,...before}=f.operation.command.instance,next=sealCreationInstance({...before,definitionDigest:definition.digest,parentHead:head,revision:before.revision+1,kaiUPulse:3,nodeStates:{...before.nodeStates,bench:initializeCreationComponents(definition,3).bench}});
 let source={status:'available' as const,instance:f.operation.command.instance,definition:f.context.definition,planDigest:f.plan.digest,source:'test-only-current-evolution'};
 const currentSources=createCreationCurrentSourcePort({read:async()=>source,authenticateCurrent:async s=>s.source==='test-only-current-evolution'&&s.instance.head===source.instance.head});
 return {...f,definition,selected,next,editedPlan:compiled.plan,currentSources,update(){source={...source,instance:next,definition,planDigest:compiled.plan.digest};},invalidate(){source={...source,source:'raw-json-unverified'};}};
}
test('controller evolves one exact admitted instance and never constructs a second copy',async()=>{
 const f=await evolutionFixture();let constructs=0,evolves=0;
 const controller=createCreationController({environment:()=>({ownerId:'owner',worldId:f.plan.worldId,spaceId:f.plan.spaceId}),journal:f.journal,authorize:async()=>f.evidence,prepare:async()=>{constructs++;return f.batch;},currentSources:f.currentSources,project:async(i,d,p)=>projectCreationPhysical(i,d,p),canReplace:async()=>true,createAdmission:()=>({execute:async op=>({status:'unknown',operationId:op.operationId}),lookup:async id=>({status:'unknown',operationId:id})}),prepareEvolution:async request=>({operationId:'evolve:actual',execute:async fence=>{assert.equal(request.source.instance.head,f.selected.head);assert.equal(await fence(),true);evolves++;f.update();return {status:'admitted',instance:f.next};}})});
 assert.equal(await controller.hydrate(f.operation.instanceId,f.plan),true);
 const result=await controller.commit(f.definition,f.editedPlan,['fixture:card'],f.selected);assert.equal(result.status,'admitted');assert.equal(evolves,1);assert.equal(constructs,0);assert.equal(controller.snapshot().projections.length,1);assert.equal(controller.snapshot().instances[f.operation.instanceId].head,f.next.head);
});
test('evolution controller refuses stale selection before dispatch and unverified successors after dispatch',async()=>{
 const f=await evolutionFixture();let calls=0;const controller=createCreationController({environment:()=>({ownerId:'owner',worldId:f.plan.worldId,spaceId:f.plan.spaceId}),journal:f.journal,authorize:async()=>f.evidence,prepare:async()=>f.batch,currentSources:f.currentSources,project:async(i,d,p)=>projectCreationPhysical(i,d,p),canReplace:async()=>true,createAdmission:()=>({execute:async op=>({status:'unknown',operationId:op.operationId}),lookup:async id=>({status:'unknown',operationId:id})}),prepareEvolution:async()=>({operationId:'evolve:unknown',execute:async()=>{calls++;f.update();f.invalidate();return {status:'admitted',instance:f.next};}})});
 assert.equal((await controller.commit(f.definition,f.editedPlan,['fixture:card'],{...f.selected,head:f.context.compileContext.sourceHead})).status,'rejected');assert.equal(calls,0);
 const result=await controller.commit(f.definition,f.editedPlan,['fixture:card'],f.selected);assert.equal(result.status,'unknown');if(result.status==='unknown')assert.equal(result.operationId,'evolve:unknown');assert.equal(calls,1);assert.equal(controller.snapshot().projections.length,0);
});
test('account change during evolution retains the real operation identity and publishes no geometry',async()=>{
 const f=await evolutionFixture();let ownerId='owner';const controller=createCreationController({environment:()=>({ownerId,worldId:f.plan.worldId,spaceId:f.plan.spaceId}),journal:f.journal,authorize:async()=>f.evidence,prepare:async()=>f.batch,currentSources:f.currentSources,project:async(i,d,p)=>projectCreationPhysical(i,d,p),createAdmission:()=>({execute:async op=>({status:'unknown',operationId:op.operationId}),lookup:async id=>({status:'unknown',operationId:id})}),prepareEvolution:async()=>({operationId:'evolve:in-flight',execute:async()=>{f.update();ownerId='other';return {status:'admitted',instance:f.next};}})});
 const result=await controller.commit(f.definition,f.editedPlan,['fixture:card'],f.selected);assert.equal(result.status,'unknown');if(result.status==='unknown')assert.equal(result.operationId,'evolve:in-flight');assert.equal(controller.snapshot().projections.length,0);
});

test('an interrupted evolution keeps its staged operation identity for lookup recovery',async()=>{
 const f=await evolutionFixture();const controller=createCreationController({environment:()=>({ownerId:'owner',worldId:f.plan.worldId,spaceId:f.plan.spaceId}),journal:f.journal,authorize:async()=>f.evidence,prepare:async()=>f.batch,currentSources:f.currentSources,project:async(i,d,p)=>projectCreationPhysical(i,d,p),createAdmission:()=>({execute:async op=>({status:'unknown',operationId:op.operationId}),lookup:async id=>({status:'unknown',operationId:id})}),prepareEvolution:async()=>({operationId:'evolve:exact-staged',execute:async()=>{throw Error('network outcome unknown');}})});
 const result=await controller.commit(f.definition,f.editedPlan,['fixture:card'],f.selected);assert.deepEqual(result,{status:'unknown',operationId:'evolve:exact-staged'});assert.equal(controller.snapshot().projections.length,0);
});
