import assert from 'node:assert/strict';
import {test} from 'node:test';
import {creationOperationContextFixture,creationOperationFixture,creationJournalFixture} from './support/creation-operation-fixtures';
import {compileCreation} from '../src/features/play/creation/compiler';
import {prepareCreationOperation,commitCreation,verifyCreationAdmission,createCreationAdmissionPort,type CreationOperation} from '../src/features/play/creation/operation';
function admitted(operation:CreationOperation){return {status:'admitted',operationId:operation.operationId,operationDigest:operation.digest,instance:operation.command.instance,successorSources:[{id:operation.instanceId,head:operation.command.instance.head,kind:'creation',parentHead:null},...operation.command.resourceSuccessors.map(r=>({id:r.id,head:r.head,kind:r.kind,parentHead:operation.expectedHeads[r.id]})),...operation.workerAllocations.filter(w=>w.work>0).map(w=>({id:w.workerId,head:`sha256:${'c'.repeat(64)}`,kind:'creature',parentHead:operation.expectedHeads[w.workerId]})),{id:`space:${operation.command.instance.spaceId}`,head:`sha256:${'d'.repeat(64)}`,kind:'space',parentHead:operation.expectedHeads[`space:${operation.command.instance.spaceId}`]}],eventIds:['fixture:event'],receipt:'explicit-test-only-receipt'};}
function portFixture(operation:CreationOperation,unknownFirst=false){let dispatchCalls=0,lookupCalls=0;const port=createCreationAdmissionPort({executeRaw:async()=>{dispatchCalls++;return unknownFirst?{status:'unknown',operationId:operation.operationId}:admitted(operation);},lookupRaw:async()=>{lookupCalls++;return admitted(operation);},authenticate:async(_op,result)=>!!result&&typeof result==='object'&&(result as {receipt?:unknown}).receipt==='explicit-test-only-receipt'});return {port,get dispatchCalls(){return dispatchCalls;},get lookupCalls(){return lookupCalls;}};}
test('construction candidate conserves exact legacy lots and bounded work',()=>{const context=creationOperationContextFixture(),result=compileCreation(context.definition,context.compileContext);assert.equal(result.status,'ready');if(result.status!=='ready')return;const original=JSON.stringify(context.lots),op=prepareCreationOperation(result.plan,context);assert.equal(op.resources.length,result.plan.requiredResources.timber);assert.equal(op.resources.reduce((n,r)=>n+r.quantity,0),op.command.instance.embeddedResources.reduce((n,r)=>n+r.quantity,0));assert.equal(op.workerAllocations.reduce((n,w)=>n+w.work,0),result.plan.requiredWork);assert.equal(op.command.instance.stage,'functional');assert.equal(op.command.resourceSuccessors.every(r=>r.spent),true);assert.equal(JSON.stringify(context.lots),original);assert.equal(Object.isFrozen(op.command.instance),true);for(const change of [{workCeiling:0},{actorId:'other'},{lots:[...context.lots,context.lots[0]]},{workers:context.workers.map(w=>({...w,ready:false}))},{compileContext:{...context.compileContext,sourceHead:`sha256:${'b'.repeat(64)}`}}])assert.throws(()=>prepareCreationOperation(result.plan,{...context,...change}));});
test('recovers unknown work without a second dispatch',async()=>{const op=creationOperationFixture(),fixture=portFixture(op,true),{journal}=creationJournalFixture();assert.equal((await commitCreation(op,fixture.port,journal)).status,'unknown');const result=await commitCreation(op,fixture.port,journal);assert.equal(fixture.dispatchCalls,1);assert.equal(fixture.lookupCalls,1);assert.equal(result.status,'admitted');});
test('forged admission cannot make a candidate physical',()=>{const op=creationOperationFixture();assert.equal(verifyCreationAdmission(op,admitted(op)).status,'unknown');assert.equal(verifyCreationAdmission(op,{status:'rejected',writes:0,operationId:op.operationId}).status,'unknown');});
test('same operation identity with different bytes never dispatches twice',async()=>{const op=creationOperationFixture(),fixture=portFixture(op),{journal}=creationJournalFixture();assert.equal((await commitCreation(op,fixture.port,journal)).status,'admitted');assert.equal((await commitCreation({...op,planDigest:`sha256:${'b'.repeat(64)}`},fixture.port,journal)).status,'rejected');assert.equal(fixture.dispatchCalls,1);});
test('durable completion failure retains exact reservations for lookup recovery',async()=>{const op=creationOperationFixture(),fixture=portFixture(op),store=creationJournalFixture();store.failCompletion();const result=await commitCreation(op,fixture.port,store.journal);assert.equal(result.status,'unknown');assert.deepEqual(store.row?.reservationRefs,op.resources.map(r=>r.id));assert.equal(store.row?.phase,'pending');assert.equal(fixture.dispatchCalls,1);});

test('journal read failure cannot report zero writes for previously dispatched work',async()=>{const op=creationOperationFixture(),fixture=portFixture(op,true),store=creationJournalFixture();await commitCreation(op,fixture.port,store.journal);const broken={...store.journal,read:async()=>{throw Error('unavailable');}};const result=await commitCreation(op,fixture.port,broken);assert.equal(result.status,'unknown');assert.equal(fixture.dispatchCalls,1);assert.deepEqual(store.row?.reservationRefs,op.resources.map(r=>r.id));});
test('two concurrent callers share one durable pending fence',async()=>{const op=creationOperationFixture(),fixture=portFixture(op),store=creationJournalFixture();const results=await Promise.all([commitCreation(op,fixture.port,store.journal),commitCreation(op,fixture.port,store.journal)]);assert.equal(fixture.dispatchCalls,1);assert.equal(results.some(r=>r.status==='admitted'),true);});

test('an unqualified production runtime reports a concrete zero-dispatch blocker',async()=>{const {createWildsCreationExecution}=await import('../src/lib/receiz/wilds-creation-execution');const operation=creationOperationFixture(),store=creationJournalFixture(),execution=createWildsCreationExecution({journal:store.journal});const result=await execution.execute(operation);assert.equal(result.status,'rejected');if(result.status==='rejected'){assert.equal(result.writes,0);assert.match(result.reason,/unqualified/);}assert.equal(store.row?.phase,'rejected');});

test('authentication verifies the captured bytes when transport data changes during await',async()=>{const op=creationOperationFixture(),raw={...admitted(op),receipt:'invalid-at-capture'};let enter!:()=>void,release!:()=>void;const started=new Promise<void>(resolve=>{enter=resolve;}),gate=new Promise<void>(resolve=>{release=resolve;});const port=createCreationAdmissionPort({executeRaw:async()=>raw,lookupRaw:async()=>raw,authenticate:async(_operation,result)=>{enter();await gate;return (result as {receipt:string}).receipt==='valid-after-capture';}});const request=port.execute(op);await started;raw.receipt='valid-after-capture';release();assert.equal((await request).status,'unknown');});

test('SDK transaction binding retains the full exact creation command including its digest',async()=>{const {verifyWildsCreationTransactionBinding}=await import('../src/lib/receiz/wilds-creation-admission');const op=creationOperationFixture(),head=`sha256:${'a'.repeat(64)}`,transaction={schema:'receiz.world.transaction.v122' as const,transactionId:'tx:fixture',worldId:op.command.instance.worldId,expectedWorldHead:head,participantHeads:Object.fromEntries(Object.entries(op.expectedHeads).filter((entry):entry is [string,string]=>entry[1]!==null)),commands:[{commandId:'command:fixture',worldId:op.command.instance.worldId,expectedWorldHead:head,actorSubjectId:'actor:owner',participantSubjectIds:Object.keys(op.expectedHeads).filter(id=>op.expectedHeads[id]!==null),causalParents:[],command:op,exactCommandBytesB64u:'fixture-only',commandDigest:head,planDigest:head,authorityDigest:head,mandateDigest:head}],registryDigest:head,reducerDigest:head,idempotencyKey:op.idempotencyKey,transactionDigest:head};assert.equal(verifyWildsCreationTransactionBinding(transaction,op),true);assert.equal(verifyWildsCreationTransactionBinding({...transaction,commands:[{...transaction.commands[0],command:{...op,actorId:'other'}}]},op),false);});
