import assert from 'node:assert/strict';
import {test} from 'node:test';
import {restoreCreationDraft,creationCompileContextForConversation} from '../src/features/play/creation/draft';
import {initialCreationConversation,reduceCreationConversation} from '../src/features/play/creation/conversation';
import {creationDefinitionFixture,creationContextFixture} from './support/creation-fixtures';
import {createCreationInstance} from '../src/features/play/creation/instance';
import {createCreationDefinition} from '../src/features/play/creation/definition';
function fixture(){const definition=creationDefinitionFixture(),context=creationContextFixture(),instance=createCreationInstance({instanceId:'selected:source',definition,ownerId:'recipient',worldId:context.worldId,spaceId:context.spaceId,pose:{position:{x:42,y:0,z:5},yaw:1},kaiUPulse:1}),{digest,...basis}=definition,edited=createCreationDefinition({...basis,nodes:[...definition.nodes,{...definition.nodes[0],id:'new'}]}),reference={instanceId:instance.instanceId,head:instance.head,definitionDigest:definition.digest};return {definition,instance,edited,reference,raw:JSON.stringify({ownerId:'recipient',spaceId:'surface',draft:'Add a bench',definition:edited,instance:reference})};}
test('a transferred evolution draft reopens exact owned identity before restoring the edited graph',async()=>{const f=fixture();let reads=0;const result=await restoreCreationDraft(f.raw,{ownerId:'recipient',spaceId:'surface'},async ref=>{reads++;assert.deepEqual(ref,f.reference);return {definition:f.definition,instance:f.instance};});assert.equal(result.status,'ready');if(result.status==='ready'){assert.equal(result.definition?.digest,f.edited.digest);assert.equal(result.selected?.definition.digest,f.definition.digest);assert.deepEqual(result.selected?.instance.pose,f.instance.pose);assert.equal(result.draft,'Add a bench');}assert.equal(reads,1);});
test('stale foreign and unavailable selection keeps original draft bytes recoverable',async()=>{const f=fixture();for(const reader of [async()=>null,async()=>({...f,instance:{...f.instance,ownerId:'foreign'}}),async()=>({...f,instance:{...f.instance,head:creationContextFixture().sourceHead}}),async()=>{throw Error('offline');}]){const result=await restoreCreationDraft(f.raw,{ownerId:'recipient',spaceId:'surface'},reader);assert.equal(result.status,'recovery');if(result.status==='recovery'){assert.equal(result.original,f.raw);assert.equal(result.draft,'Add a bench');}}});
test('unselected owner drafts remain compatible and copied foreign creator fields do not select an object',async()=>{const definition=creationDefinitionFixture(),scope={ownerId:'owner',spaceId:'surface'},raw=JSON.stringify({...scope,draft:'Make a door',definition});let reads=0;const result=await restoreCreationDraft(raw,scope,async()=>{reads++;return null;});assert.equal(result.status,'ready');assert.equal(reads,0);assert.equal((await restoreCreationDraft(raw,{ownerId:'recipient',spaceId:'surface'})).status,'recovery');assert.equal((await restoreCreationDraft(JSON.stringify({ownerId:'recipient',spaceId:'surface',draft:'copy',definition}),{ownerId:'recipient',spaceId:'surface'})).status,'recovery');});
test('multiple refinements quote against the same original selected source and source placement',()=>{const f=fixture(),initial=initialCreationConversation('recipient','surface',creationContextFixture().pose);let state=reduceCreationConversation(initial,{type:'selection',definition:f.definition,instance:f.reference,pose:f.instance.pose} as Parameters<typeof reduceCreationConversation>[1]);assert.deepEqual(state.placement,f.instance.pose);state=reduceCreationConversation(state,{type:'request',requestId:'a'});state=reduceCreationConversation(state,{type:'proposal',requestId:'a',definition:f.edited,reply:'Add a bench'});const context=creationCompileContextForConversation(state,creationContextFixture());assert.equal(context.evolution?.definition.digest,f.definition.digest);assert.equal(context.evolution?.head,f.instance.head);assert.deepEqual(context.pose,f.instance.pose);});
