import assert from 'node:assert/strict';
import { test } from 'node:test';
import { renderToStaticMarkup } from 'react-dom/server';
import { WildsCreationPanel } from '../src/features/play/creation/WildsCreationPanel';
import { initialCreationConversation } from '../src/features/play/creation/conversation';
import { creationContextFixture } from './support/creation-fixtures';
test('opens with the conversation and offers small manual controls',()=>{const state={...initialCreationConversation('owner','surface',creationContextFixture().pose),open:true};const markup=renderToStaticMarkup(<WildsCreationPanel state={state} workers={[]} cards={[]} materialCounts={{hay:0,timber:0,stone:0}} onChange={()=>{}} onAsk={()=>{}} onBuild={()=>{}} onClose={()=>{}} onManualBuild={()=>{}} canBuild={false}/>);assert.match(markup,/What would you like to build/);assert.match(markup,/Manual building/);assert.match(markup,/Choose creatures/);assert.match(markup,/Allocate resources/);assert.match(markup,/Choose object/);});
test('does not offer build success without an admission port',()=>{const state={...initialCreationConversation('owner','surface',creationContextFixture().pose),open:true,status:'preview' as const};const markup=renderToStaticMarkup(<WildsCreationPanel state={state} workers={[]} cards={[]} materialCounts={{hay:0,timber:0,stone:0}} onChange={()=>{}} onAsk={()=>{}} onBuild={()=>{}} onClose={()=>{}} onManualBuild={()=>{}} canBuild={false}/>);assert.match(markup,/<button[^>]*disabled[^>]*>Build here/);assert.match(markup,/awaiting authenticated world admission/);assert.doesNotMatch(markup,/Built successfully/);});

test('minimized conversation is one icon with an accessible reopen action',()=>{const state={...initialCreationConversation('owner','surface',creationContextFixture().pose),open:true,minimized:true};const markup=renderToStaticMarkup(<WildsCreationPanel state={state} workers={[]} cards={[]} materialCounts={{}} onChange={()=>{}} onAsk={()=>{}} onBuild={()=>{}} onClose={()=>{}} onManualBuild={()=>{}} canBuild={false}/>);assert.match(markup,/aria-label="Expand creation conversation"/);assert.equal((markup.match(/<button/g)||[]).length,1);assert.doesNotMatch(markup,/textarea|>Creation</);});

test('shows creature and resource selections next to their controls',()=>{const state={...initialCreationConversation('owner','surface',creationContextFixture().pose),open:true,workerIds:['one','two'],budget:{timber:12,stone:3}};const markup=renderToStaticMarkup(<WildsCreationPanel state={state} workers={[]} cards={[]} materialCounts={{timber:12,stone:3}} onChange={()=>{}} onAsk={()=>{}} onBuild={()=>{}} onClose={()=>{}} onManualBuild={()=>{}} canBuild={false}/>);assert.match(markup,/aria-label="2 creatures selected"[^>]*>2</);assert.match(markup,/aria-label="15 resource units allocated"[^>]*>15</);assert.match(markup,/title="Open building pieces"/);assert.doesNotMatch(markup,/<details[^>]*class="creation-manual"/);});
