import assert from 'node:assert/strict';
import {test} from 'node:test';
import {creationDefinitionFixture,creationContextFixture} from './support/creation-fixtures';
import {createCreationInstance,sealCreationInstance} from '../src/features/play/creation/instance';
import {compileCreation} from '../src/features/play/creation/compiler';
import {projectCreationPhysical} from '../src/features/play/creation/projection';
import {prepareCreationNavigation,resolveCreationMovement,findCreationRoute} from '../src/features/play/creation/navigation';
import {resolveCreationInteraction} from '../src/features/play/creation/interactions';
import {emptyCreationState} from '../src/features/play/creation/state';
function fixture(){const base=creationDefinitionFixture().nodes[0];const steps=Array.from({length:10},(_,i)=>({...base,id:`step${i}`,shape:{kind:'box' as const,width:1,height:.2,depth:.6},pose:{position:{x:0,y:i*.2,z:i*.55},yaw:0},supports:i?[`step${i-1}`]:[],behaviors:[]}));const definition=creationDefinitionFixture({nodes:steps});const result=compileCreation(definition,creationContextFixture());assert.equal(result.status,'ready');if(result.status!=='ready')throw Error('fixture');const initial=createCreationInstance({instanceId:'stairs',definition,ownerId:'owner',worldId:'wildz',spaceId:'surface',pose:result.plan.pose,kaiUPulse:1});const {head,...basis}=initial;void head;const instance=sealCreationInstance({...basis,stage:'functional'});return {definition,plan:result.plan,instance};}
test('admits connected stairs and inhabitable upper floors',()=>{const f=fixture(),projection=projectCreationPhysical(f.instance,f.definition,f.plan),runtime=prepareCreationNavigation([projection]);const route=findCreationRoute(runtime,'surface',projection.walkable[0].center,projection.walkable.at(-1)!.center);assert.equal(route.reachable,true);assert.equal(projection.spaceId,f.instance.spaceId);assert.equal(route.points.length,10);});
test('movement uses oriented solids, preserves spaces, and sweeps against tunnelling',()=>{const definition=creationDefinitionFixture(),result=compileCreation(definition,creationContextFixture());if(result.status!=='ready')throw Error('fixture');const initial=createCreationInstance({instanceId:'house',definition,ownerId:'owner',worldId:'wildz',spaceId:'surface',pose:result.plan.pose,kaiUPulse:1}),{head,...basis}=initial;void head;const projection=projectCreationPhysical(sealCreationInstance({...basis,stage:'functional'}),definition,result.plan),runtime=prepareCreationNavigation([projection]);const entry=resolveCreationMovement(runtime,'surface',{x:0,y:.15,z:-3},{x:0,y:.15,z:0});assert.equal(entry.blocked,false);const wall=resolveCreationMovement(runtime,'surface',{x:0,y:.15,z:0},{x:4,y:.15,z:0});assert.equal(wall.blocked,true);assert.ok(wall.position.x<2);const isolated=resolveCreationMovement(runtime,'cave',{x:0,y:.15,z:0},{x:4,y:.15,z:0});assert.equal(isolated.blocked,false);});
test('planned previews never become physical and broken supports remove traversal',()=>{const f=fixture(),{head,...basis}=f.instance;assert.throws(()=>projectCreationPhysical(sealCreationInstance({...basis,stage:'planned'}),f.definition,f.plan),/functional/);const states={...basis.nodeStates,step0:{...basis.nodeStates.step0,condition:0}};const damaged=sealCreationInstance({...basis,nodeStates:states,revision:1,parentHead:head});const projection=projectCreationPhysical(damaged,f.definition,f.plan);assert.equal(projection.solids.length,0);assert.equal(projection.walkable.length,0);});
test('duplicate projection heads deduplicate and conflicting heads reject',()=>{const f=fixture(),projection=projectCreationPhysical(f.instance,f.definition,f.plan);assert.equal(prepareCreationNavigation([projection,projection]).instanceCount,1);assert.throws(()=>prepareCreationNavigation([projection,{...projection,head:`sha256:${'b'.repeat(64)}`}]),/conflict/);});
test('interactions require current custody, usable components, range and matching space',()=>{const f=fixture(),state={...emptyCreationState(),definitions:{[f.definition.digest]:f.definition},instances:{stairs:f.instance},custody:{stairs:'owner'}};assert.deepEqual(resolveCreationInteraction(state,'stairs','step0',{id:'visitor',spaceId:'surface',position:{x:0,y:0,z:0}}),[]);const actions=resolveCreationInteraction(state,'stairs','step0',{id:'owner',spaceId:'surface',position:{x:0,y:0,z:0}});assert.ok(actions.some(a=>a.action==='edit'));assert.ok(!actions.some(a=>a.action==='rest'));assert.deepEqual(resolveCreationInteraction({...state,custody:{stairs:'new-owner'}},'stairs','step0',{id:'owner',spaceId:'surface',position:{x:0,y:0,z:0}}),[]);assert.deepEqual(resolveCreationInteraction(state,'stairs','step0',{id:'owner',spaceId:'cave',position:{x:0,y:0,z:0}}),[]);});

test('a sealed candidate or transport admission cannot enter the playable store',async()=>{const {createCreationPhysicalStore}=await import('../src/features/play/creation/physical-store');const {creationOperationFixture,creationOperationContextFixture}=await import('./support/creation-operation-fixtures');const operation=creationOperationFixture(),context=creationOperationContextFixture(),compiled=compileCreation(context.definition,context.compileContext);if(compiled.status!=='ready')throw Error('fixture');let projectCalls=0;const store=createCreationPhysicalStore({project:async(instance,definition,plan)=>{projectCalls++;return projectCreationPhysical(instance,definition,plan);}});assert.equal(await store.adopt(operation,{status:'admitted',operationId:operation.operationId,operationDigest:operation.digest,instance:operation.command.instance,successorSources:[],eventIds:[],receipt:{canonical:true}},compiled.plan),false);assert.equal(projectCalls,0);assert.equal(store.snapshot().projections.length,0);});

test('projection rejects altered plan stages even when digest text is unchanged',()=>{const f=fixture();assert.throws(()=>projectCreationPhysical(f.instance,f.definition,{...f.plan,stages:[['step9']]}),/seal/);});
