import assert from 'node:assert/strict';
import {test} from 'node:test';
import {KAI_N_DAY_MICRO} from '../src/features/play/kai-klok-moment';
import {createPlayerBreaths,advancePlayerBreaths,spendPlayerBreaths,playerBreathEnergy,playerBreathReadout,restorePlayerBreaths} from '../src/features/play/player-breath-energy';
import {applyWildsInput,initialPlayState,serializePlayState,restorePlayState} from '../src/features/play/game-state';
const DAY=Number(KAI_N_DAY_MICRO),BASE=DAY*100;
test('17491 breath allocation follows the exact existing Kai day without clock drift',()=>{const s=createPlayerBreaths(BASE,100);assert.equal(playerBreathReadout(s,BASE).breathsPerDay,17491);assert.equal(playerBreathReadout(s,BASE+DAY-1).elapsedBreaths,17490);assert.equal(playerBreathReadout(s,BASE+DAY).elapsedBreaths,0);assert.equal(playerBreathReadout(s,BASE+DAY).day,101);});
test('split clock advancement conserves fractional recovery and never multiplies it',()=>{let split=spendPlayerBreaths(createPlayerBreaths(BASE,100),1000);split=advancePlayerBreaths(split,BASE,'camp');const start=split,end=BASE+1_000_000;for(let i=1;i<=100;i++)split=advancePlayerBreaths(split,BASE+i*10_000);const once=advancePlayerBreaths(start,end);assert.deepEqual(split,once);assert.ok(split.reserveMicroBreaths>start.reserveMicroBreaths);});
test('rest clicks grant no immediate energy and repeated ticks at the same pulse are inert',()=>{const s=createPlayerBreaths(BASE,20),rest=advancePlayerBreaths(s,BASE,'camp');assert.equal(playerBreathEnergy(rest),20);assert.deepEqual(advancePlayerBreaths(rest,BASE,'camp'),rest);assert.deepEqual(advancePlayerBreaths(rest,BASE-1),rest);});
test('active offline time drains only analytical metabolism and rest is bounded by capacity',()=>{const s=createPlayerBreaths(BASE,100),idle=advancePlayerBreaths(s,BASE+DAY);assert.equal(playerBreathEnergy(idle),95);const resting=advancePlayerBreaths(createPlayerBreaths(BASE,20),BASE,'bed');assert.equal(playerBreathEnergy(advancePlayerBreaths(resting,BASE+DAY*1000)),100);});
test('actual walking distance costs the same across input rates and blocked input costs nothing',()=>{const a=spendPlayerBreaths(createPlayerBreaths(BASE,100),10),b=Array.from({length:20}).reduce<ReturnType<typeof createPlayerBreaths>>(s=>spendPlayerBreaths(s,.5),createPlayerBreaths(BASE,100));assert.equal(a.reserveMicroBreaths,b.reserveMicroBreaths);const state={...initialPlayState,playerBreaths:createPlayerBreaths(BASE,84)};const blocked=applyWildsInput(state,{type:'move-vector',x:0,z:0,kaiUPulse:BASE});assert.equal(blocked.energy,84);assert.equal(blocked.playerBreaths!.spentMicroBreaths,0);});
test('gameplay movement replaces one-energy-per-input and the reserve persists through save restoration',()=>{const s={...initialPlayState,playerBreaths:createPlayerBreaths(BASE,84)},next=applyWildsInput(s,{type:'move',direction:'east',kaiUPulse:BASE});assert.ok(next.energy>83.9&&next.energy<84);assert.ok(next.playerBreaths!.spentMicroBreaths>0);const restored=restorePlayState(serializePlayState(next));assert.equal(restored.playerBreaths!.reserveMicroBreaths,next.playerBreaths!.reserveMicroBreaths);});
test('camp cannot repeatedly heal or refill the player at one pulse',()=>{const start={...initialPlayState,energy:20,playerBreaths:createPlayerBreaths(BASE,20)};const once=applyWildsInput(start,{type:'rest',kaiUPulse:BASE}),twice=applyWildsInput(once,{type:'rest',kaiUPulse:BASE});assert.equal(once.energy,20);assert.equal(twice.energy,20);assert.equal(once.inventory,start.inventory);assert.equal(twice.inventory,start.inventory);const recovered=applyWildsInput(twice,{type:'energy-tick',kaiUPulse:BASE+100_000_000});assert.ok(recovered.energy>20);assert.equal(recovered.actionHistory.length,twice.actionHistory.length);});
test('save migration preserves legacy energy and rejects invalid breath state',()=>{const migrated=restorePlayerBreaths(undefined,BASE,42);assert.equal(playerBreathEnergy(migrated),42);const altered=restorePlayerBreaths({...migrated,reserveMicroBreaths:Infinity},BASE,42);assert.equal(playerBreathEnergy(altered),42);assert.equal(restorePlayerBreaths(migrated,BASE,1),migrated);});

test('untimed legacy housekeeping cannot charge time from Kai genesis on its first clock observation',()=>{const housekeeping=applyWildsInput(initialPlayState,{type:'dismiss-reveal'});const rooted=applyWildsInput(housekeeping,{type:'energy-tick',kaiUPulse:BASE});assert.equal(rooted.energy,initialPlayState.energy);assert.equal(rooted.playerBreaths!.lastKaiUPulse,BASE);});

test('a nearly empty reserve cannot pay for a full movement step',()=>{const start={...initialPlayState,energy:.000001,playerBreaths:createPlayerBreaths(BASE,.000001)};const moved=applyWildsInput(start,{type:'move',direction:'east',kaiUPulse:BASE});assert.deepEqual(moved.player,start.player);assert.equal(moved.playerBreaths!.reserveMicroBreaths,start.playerBreaths.reserveMicroBreaths);});
