import assert from 'node:assert/strict';
import {test} from 'node:test';
import {creationInstanceFixture,creationStateFixture,creationAuthorityFixture,creationSourceHead} from './support/creation-instance-fixtures';
import {sealCreationInstance,verifyCreationInstance} from '../src/features/play/creation/instance';
import {reduceCreationOperation,type CreationCommand} from '../src/features/play/creation/state';
function useCommand(state:ReturnType<typeof creationStateFixture>):CreationCommand{const instance=state.instances['instance:fixture'];return {action:'use',nodeId:'room',operationId:'use:fixture',actorId:'owner',instanceId:instance.instanceId,expectedHeads:{[instance.instanceId]:instance.head,'actor:owner':creationSourceHead},kaiUPulse:2};}
test('creation instance identity is deterministic and mutation/schema tampering rejects',()=>{const instance=creationInstanceFixture();assert.deepEqual(instance,creationInstanceFixture());assert.equal(verifyCreationInstance(instance),true);assert.equal(verifyCreationInstance({...instance,ownerId:'other'}),false);assert.equal(verifyCreationInstance({...instance,schema:'future'}),false);const {head,...basis}=instance;assert.throws(()=>sealCreationInstance({...basis,nodeStates:{room:{...basis.nodeStates.room,kind:'unknown'} as never}}),/component/);assert.equal(Object.isFrozen(instance.nodeStates),true);});
test('rejects use of a destroyed instance',()=>{const before=creationStateFixture(),old=before.instances['instance:fixture'],{head,...basis}=old;const instance=sealCreationInstance({...basis,stage:'destroyed',revision:1,parentHead:head});const state={...before,instances:{[instance.instanceId]:instance}};const transition=reduceCreationOperation(state,useCommand(state),creationAuthorityFixture(state));assert.equal(transition.status,'rejected');assert.equal(transition.state,state);assert.deepEqual(transition.state,state);});
test('lineage proposals are immutable and replay is exact with no physical admission',()=>{const state=creationStateFixture(),instance=state.instances['instance:fixture'];const command:CreationCommand={...useCommand(state),action:'advance',stage:'building'};const context=creationAuthorityFixture(state),before=JSON.stringify(state),a=reduceCreationOperation(state,command,context),b=reduceCreationOperation(state,command,context);assert.equal(a.status,'proposed');assert.deepEqual(a,b);assert.equal(JSON.stringify(state),before);if(a.status==='proposed'){const next=a.state.instances[instance.instanceId];assert.equal(next.parentHead,instance.head);assert.equal(next.revision,1);assert.equal(verifyCreationInstance(next),true);const replay=reduceCreationOperation(a.state,command,creationAuthorityFixture(a.state));assert.equal(replay.status,'proposed');assert.equal(replay.state,a.state);assert.deepEqual(replay.successorSources,[]);}});
test('stale heads and unauthenticated source references retain exact state',()=>{const state=creationStateFixture(),command=useCommand(state),context=creationAuthorityFixture(state);for(const input of [{...command,expectedHeads:{...command.expectedHeads,[command.instanceId]:creationSourceHead}},command]){const result=reduceCreationOperation(state,input,{...context,verifySource:()=>false});assert.equal(result.status,'rejected');assert.equal(result.state,state);}});
