import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createCreationInstance, sealCreationInstance } from '../src/features/play/creation/instance';
import { creationDefinitionFixture } from './support/creation-fixtures';
import { emptyCreationState } from '../src/features/play/creation/state';
import { sealCreationTransferOffer, proposeCreationTransferAcceptance, CREATION_TRANSFER_RULE_ID, CREATION_TRANSFER_RULE_HEAD } from '../src/features/play/creation/transfer';
import { sealCreationOccupancyGrant } from '../src/features/play/creation/occupancy';
const actorHead = `sha256:${'b'.repeat(64)}`;
function fixture() { const planned = createCreationInstance({ instanceId: 'home', definition: creationDefinitionFixture(), ownerId: 'owner', worldId: 'wildz', spaceId: 'surface', pose: { position: { x: 0, y: 0, z: 0 }, yaw: 0 }, kaiUPulse: 0 }), { head, ...basis } = planned, instance = sealCreationInstance({ ...basis, revision: 1, parentHead: head, stage: 'functional', nodeStates: { room: { kind: 'habitat', version: 1, nodeId: 'room', condition: 74, supportIds: [], occupantIds: ['visitor'], capacity: 2 } }, embeddedResources: [{ id: 'wood', head: actorHead, kind: 'timber', quantity: 7 }] }); const grant = sealCreationOccupancyGrant({ grantId: 'grant', instanceId: 'home', ownerId: 'owner', subjectId: 'visitor', roomNodeIds: ['room'], permissions: ['inhabit'], expiresAtKaiUPulse: null, revision: 0, parentHead: null, kaiUPulse: 0 }); const state = { ...emptyCreationState(), instances: { home: instance }, custody: { home: 'owner' }, occupancyGrants: { grant }, contributions: {} }; const offer = sealCreationTransferOffer({ offerId: 'gift', instanceId: 'home', expectedHead: instance.head, from: 'owner', to: 'recipient', rights: 'instance', expiresAtKaiUPulse: 100, operationId: 'gift:accept', kaiUPulse: 1 }); const sources = [{ id: 'home', head: instance.head, kind: 'creation' }, { id: 'actor:recipient', head: actorHead, kind: 'actor' }, { id: 'gift', head: offer.head, kind: 'creation-transfer-offer' }, { id: `rule:${CREATION_TRANSFER_RULE_ID}`, head: CREATION_TRANSFER_RULE_HEAD, kind: 'rule' }]; const context = { actorId: 'recipient', rules: { [CREATION_TRANSFER_RULE_ID]: CREATION_TRANSFER_RULE_HEAD }, sources, verifySource: (s: {
        id: string;
        head: string;
        kind: string;
    }) => sources.some(v => v.id === s.id && v.head === s.head && v.kind === s.kind), mandates: [] }; return { instance, state, offer, context, request: { operationId: 'gift:accept', actorId: 'recipient', expectedActorHead: actorHead, kaiUPulse: 2 } }; }
test('accepted transfer preserves contents and occupant grants', () => { const f = fixture(), result = proposeCreationTransferAcceptance(f.state, f.offer, f.request, f.context); assert.equal(result.status, 'proposed'); if (result.status !== 'proposed')
    return; const next = result.state.instances.home; assert.equal(next.ownerId, 'recipient'); assert.equal(next.creatorId, 'owner'); assert.equal(next.stewardId, 'recipient'); assert.deepEqual(next.nodeStates, f.instance.nodeStates); assert.deepEqual(next.embeddedResources, f.instance.embeddedResources); assert.deepEqual(result.state.occupancyGrants, f.state.occupancyGrants); assert.equal(next.parentHead, f.instance.head); assert.equal(result.state.custody.home, 'recipient'); });
test('wrong recipient expired offer and unauthenticated offer produce no successor', () => { const f = fixture(); for (const r of [{ ...f.request, actorId: 'other' }, { ...f.request, kaiUPulse: 100 }])
    assert.equal(proposeCreationTransferAcceptance(f.state, f.offer, r, f.context).status, 'rejected'); assert.equal(proposeCreationTransferAcceptance(f.state, f.offer, f.request, { ...f.context, verifySource: () => false }).status, 'rejected'); });
test('moving or equipping after an offer makes its exact head stale', () => { const f = fixture(), { head, ...basis } = f.instance, current = sealCreationInstance({ ...basis, revision: 2, parentHead: head, pose: { position: { x: 1, y: 0, z: 0 }, yaw: 0 } }); assert.equal(proposeCreationTransferAcceptance({ ...f.state, instances: { home: current } }, f.offer, f.request, f.context).status, 'rejected'); });
test('acceptance replay uses current verified custody and cannot transfer twice', () => { const f = fixture(), first = proposeCreationTransferAcceptance(f.state, f.offer, f.request, f.context); if (first.status !== 'proposed')
    throw Error('fixture'); const head = first.state.instances.home.head, context = { ...f.context, sources: f.context.sources.map(s => s.id === 'home' ? { ...s, head } : s), verifySource: () => true }; const retry = proposeCreationTransferAcceptance(first.state, f.offer, f.request, context); assert.equal(retry.status, 'proposed'); assert.equal(retry.state, first.state); assert.equal(proposeCreationTransferAcceptance(first.state, f.offer, { ...f.request, operationId: 'different' }, context).status, 'rejected'); });
