import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createCreationInstance, sealCreationInstance } from '../src/features/play/creation/instance';
import { creationDefinitionFixture } from './support/creation-fixtures';
import { canAccessCreation, creationAccessPreset } from '../src/features/play/creation/access';
import { canInhabitCreationRoom, sealCreationOccupancyGrant } from '../src/features/play/creation/occupancy';
const head = `sha256:${'a'.repeat(64)}`;
function fixture() { const planned = createCreationInstance({ instanceId: 'home', definition: creationDefinitionFixture(), ownerId: 'owner', worldId: 'wildz', spaceId: 'surface', pose: { position: { x: 0, y: 0, z: 0 }, yaw: 0 }, kaiUPulse: 0 }); const { head: h, ...basis } = planned; return sealCreationInstance({ ...basis, stage: 'functional', revision: 1, parentHead: h, nodeStates: { room: { kind: 'habitat', version: 1, nodeId: 'room', condition: 100, supportIds: [], occupantIds: [], capacity: 2 } } }); }
test('a public visitor cannot demolish the creation', () => { const instance = fixture(); assert.equal(canAccessCreation(instance, 'visitor', 'visit', 1), true); assert.equal(canAccessCreation(instance, 'visitor', 'demolish', 1), false); assert.equal(canAccessCreation(instance, 'visitor', 'edit', 1), false); assert.equal(canAccessCreation(instance, 'visitor', 'harvest', 1), false); assert.equal(canAccessCreation(instance, 'owner', 'demolish', 1), true); });
test('sharing presets grant explicit use without granting alteration', () => { const original = fixture(), { head: h, ...basis } = original, instance = sealCreationInstance({ ...basis, access: creationAccessPreset('public'), parentHead: h, revision: 2 }); assert.equal(canAccessCreation(instance, 'visitor', 'use', 1), true); assert.equal(canAccessCreation(instance, 'visitor', 'harvest', 1), true); assert.equal(canAccessCreation(instance, 'visitor', 'edit', 1), false); assert.equal(canAccessCreation(instance, 'visitor', 'inhabit', 1), false); });
test('occupancy is verified room-specific and expires without restoring an old grant', () => { const instance = fixture(), grant = sealCreationOccupancyGrant({ grantId: 'grant', instanceId: 'home', ownerId: 'owner', subjectId: 'visitor', roomNodeIds: ['room'], permissions: ['inhabit', 'use'], expiresAtKaiUPulse: 10, revision: 0, parentHead: null, kaiUPulse: 0 }); const verified = (id: string, h: string) => id === 'grant' && h === grant.head; assert.equal(canInhabitCreationRoom(instance, 'visitor', 'room', 1, [grant], verified), true); assert.equal(canInhabitCreationRoom(instance, 'visitor', 'elsewhere', 1, [grant], verified), false); assert.equal(canInhabitCreationRoom(instance, 'visitor', 'room', 10, [grant], verified), false); assert.equal(canInhabitCreationRoom(instance, 'visitor', 'room', 1, [grant], () => false), false); const { head: g, ...basis } = grant; const revoked = sealCreationOccupancyGrant({ ...basis, permissions: [], revision: 1, parentHead: g, kaiUPulse: 2 }); assert.equal(canInhabitCreationRoom(instance, 'visitor', 'room', 3, [revoked], () => true), false); });
test('invalid time, unknown subjects, and destroyed places cannot grant access', () => { const original = fixture(), { head: h, ...basis } = original, destroyed = sealCreationInstance({ ...basis, stage: 'destroyed', parentHead: h, revision: 2 }); assert.equal(canAccessCreation(original, 'visitor', 'visit', NaN), false); assert.equal(canAccessCreation(original, '', 'visit', 1), false); assert.equal(canAccessCreation(destroyed, 'owner', 'visit', 1), false); assert.equal(canAccessCreation(original, 'visitor', 'visit', -1), false); });
