import Link from "next/link";
import { publicPageMetadata } from "@/lib/wildz/search-metadata";
import { WILDS_V11_CREATURE_PUBLIC_PARAMETERS } from "@/features/play/wilds-creature-generator-v11";
import styles from "../v11-reader.module.css";

export const metadata = publicPageMetadata(
  "Wildz Creatures — One-of-One Companions",
  "Every Wildz creature has its own identity, appearance, first meeting, and life shaped by the journey you share.",
  "/creatures"
);

export default function CreaturesPage() {
  return <main className={styles.page}>
    <nav aria-label="Site navigation" className={styles.nav}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link aria-current="page" prefetch={false} href="/creatures">Creatures</Link><Link prefetch={false} href="/conformance">Rarity & proof</Link><Link prefetch={false} href="/">Play</Link></nav>
    <header className={styles.hero}><span className={styles.eyebrow}>THE CREATURES</span><h1>Meet someone, not something.</h1><p>Every companion is an individual. Where you met, how they look and move, what they love, and what you experience together all belong to that creature’s own story.</p><Link prefetch={false} href="/conformance">Explore rarity and exact odds →</Link></header>
    <section className={styles.section}><h2>Everyone begins with a companion</h2><p className={styles.lede}>Your first creature is always Trail, the starting rarity class. It joins you as a guaranteed companion; finding creatures in the world follows the encounter odds.</p><p>A creature you already know keeps its identity, class, and history. Saving your journey again does not make it a different creature or reroll its rarity.</p></section>
    <section className={styles.section}><h2>What does “one of one” mean?</h2><p>A creature has its own permanent identity and a record of its first encounter. Its features grow from an individual seed: lineage, body, color, markings, voice, temperament, abilities, and more. The moments that follow make its history its own.</p><div className={styles.featureGrid}><article><strong>A place</strong><p>Its recorded encounter connects the individual to a real site in the world.</p></article><article><strong>A presence</strong><p>Shape, movement, surface details, and personality give it a recognizable way of being.</p></article><article><strong>A life</strong><p>Care, exploration, relationships, battles, and choices add to its history.</p></article></div><p>Two creatures may share a color or a familiar silhouette. “One of one” means they are distinct individuals with distinct origins and histories; it is not a claim that every visible feature can never resemble another’s.</p></section>
    <section className={styles.section}><h2>A world of possibilities</h2><p>The world can keep giving new encounters as you explore. A creature takes shape when you discover it; Wildz does not need to hold every possible creature in memory.</p><p>Rarity describes the chance of its class at the place where you met. It does not secretly raise its starting statistics or put a price on the creature. Personality, abilities, and what you do together carry their own value.</p><details className={styles.deepDive}><summary>Explore the creature creation details</summary><p>Each individual’s encounter determines a repeatable starting set of traits. These are the published ranges:</p><dl>{WILDS_V11_CREATURE_PUBLIC_PARAMETERS.map(parameter => <div className={styles.factLine} key={parameter.name}><dt>{parameter.name}<br /><small>{parameter.value}</small></dt><dd>{parameter.explanation}</dd></div>)}</dl></details></section>
    <section className={styles.section}><h2>A companion you can feel beside you</h2><p>Movement, posture, voice, and reactions reveal a creature’s needs and temperament. Rest feels different from play; a favorite habitat feels different from a difficult one. Care matters because its present condition and past experiences matter.</p><p>Important moments stay with your companion. The little things—breathing, glancing, and moving beside you—make it feel alive between those moments.</p></section>
    <section className={styles.section}><h2>Return to where you met</h2><p>Bring a companion back to a known first meeting place after time away, and the return can become a homecoming. You can remember the place together and make a choice that belongs to this visit. Coming back does not create a duplicate creature or another rarity roll.</p><div className={styles.callout}><strong>A meeting place has to be known</strong><p>A recorded first encounter tells us where you met, not where the creature was born. If that place was never established, Wildz leaves it unknown instead of making up a memory.</p></div><p>The same individual keeps its story if it changes hands. A companion that has retired deserves remembrance rather than a scene that treats it as still traveling.</p><Link prefetch={false} href="/world">Explore the world you share →</Link></section>
    <footer className={styles.footer}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link prefetch={false} href="/conformance">Rarity & proof</Link><Link prefetch={false} href="/about">About</Link><Link prefetch={false} href="/guide">Guide</Link></footer>
  </main>;
}
