import Link from "next/link";
import { publicPageMetadata } from "@/lib/wildz/search-metadata";
import { WILDS_V11_CREATURE_PUBLIC_PARAMETERS } from "@/features/play/wilds-creature-generator-v11";
import styles from "../v11-reader.module.css";

export const metadata = publicPageMetadata("Wildz Creatures — One-of-One Companions & Living History", "How Wildz creatures gain individual identity, rarity, body and behavior, a first meeting place, and continuity from v10 to v11.", "/creatures");

export default function CreaturesPage() {
  return <main className={styles.page}>
    <nav aria-label="Site navigation" className={styles.nav}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link aria-current="page" prefetch={false} href="/creatures">Creatures</Link><Link prefetch={false} href="/conformance">Conformance</Link><Link prefetch={false} href="/">Play</Link></nav>
    <header className={styles.hero}><h1>No two meetings are the same.</h1><p>A Wildz companion has a canonical identity and a history that belongs to that individual. A class tells you how unlikely an encounter was at its site; it never tells you everything that creature can become.</p><Link prefetch={false} href="/conformance">Read the exact rarity law →</Link></header>
    <section className={styles.section}><h2>First, a companion for everyone</h2><p className={styles.lede}>Your starter is always Trail, the entry class. It is a guaranteed grant so that every journey begins with a companion, outside the random encounter odds.</p><p>Historic v10 starters keep their original class and proof. A v11 resave cannot silently lower a creature that already exists. New discoveries use the v11 law at the encounter site; even near the origin, the rarest classes retain a chance.</p></section>
    <section className={styles.section}><h2>What makes one “one of one”?</h2><p>Identity is the exact individual record, not a promise that every silhouette is visibly unique from every possible angle. A signed v11 encounter binds a player, site, slot, and deterministic creature seed. From that seed, a creature can have a particular mix of lineage, shape, coloration, traits, capabilities, and temperament. Its later experiences add a history that another creature cannot inherit by resemblance.</p><div className={styles.featureGrid}><article><strong>Origin</strong><p>The encountered site and signed draw ground where and under which law the meeting happened.</p></article><article><strong>Body</strong><p>Lineage, proportions, palette, markings, and animation are drawn from an individual seed and living state.</p></article><article><strong>Life</strong><p>Care, rest, exploration, battles, relationships, and admitted changes build that creature’s own timeline.</p></article></div><p>The addressable world and seed space allow extraordinarily many combinations. “One of one” refers to a distinct canonical creature and its provenance; visual traits can overlap, and infinite mathematical inputs do not mean infinite creatures are rendered at once.</p></section>
    <section className={styles.section}><h2>The generation grammar</h2><p>These are the published starting ranges for v11 births. A seed selects one value in each domain; the complete site address and player scope remain in the birth record. The system generates one creature at a time, without searching or storing the possible space.</p><dl>{WILDS_V11_CREATURE_PUBLIC_PARAMETERS.map(parameter => <div className={styles.factLine} key={parameter.name}><dt>{parameter.name}<br /><small>{parameter.value}</small></dt><dd>{parameter.explanation}</dd></div>)}</dl><p>Rarity is selected before this grammar and never scales the base stat range. A creature’s later care, abilities, relationships, and growth are separate from its birth class.</p></section>
    <section className={styles.section}><h2>A living companion responds</h2><p>A creature should feel present in a place: moving with a body, noticing nearby conditions, responding in ways shaped by temperament and needs, and recovering after exertion. Care and play matter because its state and history matter, not because rarity alone sets its worth.</p><p>Actions need visible cause and consequence. A pause, a change in posture or voice, a preference for a habitat, or a refusal when exhausted can tell you more about a companion than a stat line. Significant changes belong in its durable history; moment-to-moment animation should remain responsive without writing proof on every frame.</p></section>
    <section className={styles.section}><h2>When you return to where you met</h2><p>Bring a companion to its proven first meeting site and the place can become a homecoming: a remembered landmark, an altered reaction, and a choice to rest, follow an old trail, or investigate what changed. The first completed visit becomes a distinct history event; later visits can respond to the creature and the current world without issuing another rarity roll or a duplicate birth.</p><div className={styles.callout}><strong>Meeting place, not birthplace</strong><p>A verified encounter site proves where the player first met that creature. It does not claim where the creature was born. When a legacy record lacks a proven location, the page and card must say it is unknown rather than invent one.</p></div><p>If the creature has changed hands, its provenance remains attached to the same individual. A retired companion’s place may become a memorial, never a scene that pretends it is still active.</p></section>
    <section className={styles.section}><h2>Your v10 companions continue</h2><p>Older cards can be resaved with a v11 continuity projection. Their original identity, proof digest, rarity, and history stay under the law that issued them. A verified v10 version 3 discovery location can ground a first meeting place. Older variants without a proven location show “unknown”; a personal journal recollection remains separate from proof.</p><p>The continuity projection is deterministic and idempotent. It does not mint a second creature, create a fresh v11 encounter signature, or reroll its original rarity.</p><Link prefetch={false} href="/world">Explore how world addresses work →</Link></section>
    <footer className={styles.footer}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link prefetch={false} href="/conformance">Conformance</Link><Link prefetch={false} href="/about">About</Link><Link prefetch={false} href="/guide">Guide</Link></footer>
  </main>;
}
