"use client";
import { useEffect, useState } from "react";
import type { WildzListing } from "@/features/market/wildz-market";
import { WildzTradeConfirm } from "@/features/market/WildzTradeConfirm";
import type { PublicWildzCard } from "@/features/profile/public-profile";

export function WildzMarketSheet({ listings: initialListings, buyer, ownedCards }: { listings: WildzListing[]; buyer: string; ownedCards: PublicWildzCard[] }) {
  const [listings, setListings] = useState(initialListings); const [selected, setSelected] = useState<WildzListing | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [assetId, setAssetId] = useState(ownedCards[0]?.id ?? ""); const [price, setPrice] = useState("5.00");
  useEffect(() => { let active = true; void fetch("/api/market/listings").then((response) => response.json()).then((result: { listings?: WildzListing[] }) => { if (active && Array.isArray(result.listings)) setListings(result.listings); }).catch(() => {}); return () => { active = false; }; }, []);
  const checkout = async () => { if (!selected) return; setBusy(true); setMessage(""); try { const response = await fetch("/api/market/checkout", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `checkout:${selected.id}:${buyer}` }, body: JSON.stringify({ listing: selected, buyer, expectedRevision: selected.revision, idempotencyKey: `trade:${selected.id}:${buyer}` }) }); const result = await response.json() as { status?: string }; setMessage(result.status === "settled" ? "Trade settled. The asset is now in your Vault." : "Receiz payment is not configured. No ownership changed."); } catch { setMessage("Checkout could not be reached. No ownership changed."); } finally { setBusy(false); } };
  const list = async () => { const card = ownedCards.find((item) => item.id === assetId); if (!card) return; setBusy(true); try { const idempotencyKey = `list:${buyer}:${card.id}:${Date.now()}`; const response = await fetch("/api/market/listings", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": idempotencyKey }, body: JSON.stringify({ actor: buyer, owner: buyer, assetId: card.id, proofDigest: card.proofDigest, priceCents: Math.round(Number(price) * 100), currency: "USD", expectedRevision: 0, idempotencyKey }) }); const listing = await response.json() as WildzListing & { error?: string }; if (!response.ok) throw new Error(listing.error); setListings((current) => [listing, ...current]); setMessage("Listed. Other explorers can now offer, trade, or buy."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Listing failed."); } finally { setBusy(false); } };
  return <div className="wildz-market-sheet"><header><div><span>Player market</span><h2>Trade on the trail</h2></div><b>{listings.length} nearby</b></header>
    {ownedCards.length ? <div className="wildz-listing-composer"><select value={assetId} onChange={(event) => setAssetId(event.target.value)}>{ownedCards.map((card) => <option value={card.id} key={card.id}>{card.name}</option>)}</select><label><span>$</span><input inputMode="decimal" value={price} onChange={(event) => setPrice(event.target.value)} aria-label="Listing price" /></label><button type="button" disabled={busy} onClick={() => void list()}>List</button></div> : null}
    <div className="wildz-market-list">{listings.length ? listings.map((listing) => <button type="button" key={listing.id} onClick={() => setSelected(listing)}><i>✦</i><span><strong>{listing.assetId}</strong><small>{listing.seller}</small></span><b>${(listing.priceCents / 100).toFixed(2)}</b></button>) : <p className="wildz-sheet-empty">No nearby listings yet. List a verified companion from your Vault.</p>}</div>
    {selected ? <WildzTradeConfirm listing={selected} busy={busy} onConfirm={() => void checkout()} /> : null}{message ? <p role="status" className="wildz-market-status">{message}</p> : null}
  </div>;
}
