import Link from "next/link";
import { publicPageMetadata } from "@/lib/wildz/search-metadata";
import { publicRarityTableV11, WILDS_RARITY_BANDS_V11, WILDS_RARITY_CLASSES_V11 } from "@/features/play/wilds-v11-conformance";
import ProofChecker from "./ProofChecker";
import styles from "../v11-reader.module.css";

export const metadata = publicPageMetadata(
  "Wildz Rarity & Proof — Every Class, Every Chance",
  "See the exact chance of every creature rarity class by location, learn what the odds mean, and check an encounter proof in your browser.",
  "/conformance"
);

const BANDS = [
  { key: "origin", title: "Near home", range: "under 25 regions", detail: "The starting area has a chance at every rarity." },
  { key: "wilds", title: "Wilds", range: "25 to under 125 regions", detail: "The rarer classes become more likely as you venture outward." },
  { key: "deep-wilds", title: "Deep wilds", range: "125 to under 500 regions", detail: "The chances improve again beyond the inner world." },
  { key: "frontier", title: "Frontier", range: "500 regions and beyond", detail: "These are the best odds. Distance never guarantees a class." }
] as const;
const CLASS_NAME = { trail: "Trail", uncommon: "Uncommon", rare: "Rare", mythic: "Mythic", eternal: "Eternal" } as const;
const DATA = publicRarityTableV11();

function odds(numerator: string, denominator: string) {
  return `${Number(numerator).toLocaleString("en-US")} in ${Number(denominator).toLocaleString("en-US")}`;
}

export default function ConformancePage() {
  return <main className={styles.page}>
    <nav aria-label="Site navigation" className={styles.nav}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link prefetch={false} href="/creatures">Creatures</Link><Link aria-current="page" prefetch={false} href="/conformance">Rarity & proof</Link><Link prefetch={false} href="/">Play</Link></nav>
    <header className={styles.hero}><span className={styles.eyebrow}>RARITY & PROOF</span><h1>Know the odds. Feel the discovery.</h1><p>Every eligible encounter site has a chance at every class. Distance improves the chance of finding the rarest creatures, while each meeting remains its own surprise. The complete odds are here for everyone.</p><Link prefetch={false} href="/creatures">What makes a creature one of one →</Link></header>
    <section className={styles.section}><h2>The rarest frontier encounters</h2><p className={styles.lede}>Even at the best possible distance, these meetings are extraordinary.</p><div className={styles.featureGrid}><article className={styles.rareAccent}><strong>Rare</strong><p>1 in 1,000 eligible encounters</p></article><article className={styles.mythicAccent}><strong>Mythic</strong><p>1 in 100,000 eligible encounters</p></article><article className={styles.eternalAccent}><strong>Eternal</strong><p>1 in 1,000,000 eligible encounters</p></article></div><p>Closer to the starting area, each is even less likely. None is guaranteed by traveling far or by trying a particular number of times.</p></section>
    <section className={styles.section}><h2>Every class, at every distance</h2><p>Read across a row to see how a class changes across the world. These numbers describe the class of one eligible encounter. They are not capture success rates, prices, or a promise about a streak of attempts.</p><p className={styles.swipeHint}>Swipe the table to see every distance →</p><div className={styles.tableWrap}><table className={styles.odds}><caption className={styles.tableCaption}>Exact chance for each rarity class and distance band</caption><thead><tr><th scope="col">Class</th>{BANDS.map(b => <th key={b.key} scope="col">{b.title}<small>{b.range}</small></th>)}</tr></thead><tbody>{WILDS_RARITY_CLASSES_V11.map(className => <tr className={styles[className]} key={className}><th scope="row">{CLASS_NAME[className]}</th>{WILDS_RARITY_BANDS_V11.map(band => { const row = DATA.find(item => item.band === band && item.className === className)!; return <td key={band}><strong>{odds(row.numerator, row.denominator)}</strong><small>{row.exactProbability} · scarcity {row.scarcityBits.toFixed(2)}</small></td>; })}</tr>)}</tbody></table></div><p className={styles.oddsNote}>All five class counts add up to 10,000,000 possible draw values in each band. A starter is a guaranteed Trail companion and is outside these encounter odds.</p></section>
    <section className={styles.section}><h2>Why location matters</h2><p>Wildz measures how far the encounter site is from the starting region. The site’s region determines the distance band; your personal travel total does not change a site’s chance. A region spans 24 world units, and the Frontier begins 500 regions away, about 12,000 world units.</p><div className={styles.bandGrid}>{BANDS.map(b => <article key={b.key}><h3>{b.title}</h3><small>{b.range}</small><p>{b.detail}</p></article>)}</div><details className={styles.deepDive}><summary>See the exact distance rule</summary><p>For a site in region (x, z), the game compares x² + z² with 25², 125², and 500² using whole numbers. This works in every direction without rounding a distant address. A position inside the same region does not change its band.</p></details></section>
    <section className={styles.section}><h2>Rarity measures scarcity</h2><p>The scarcity score describes how surprising a class is at its site. It does not assign a cash value, decide a creature’s personality, or give rare creatures a hidden boost to their starting statistics.</p><details className={styles.deepDive}><summary>See how the score is calculated</summary><code className={styles.formula}>scarcity score = −log₂(class chance)</code><p>The displayed score is rounded to two decimal places. The actual draw uses exact whole-number counts, with no rounding when a class is chosen. For comparison, near home the chances are Rare 1 in 10,000, Mythic 1 in 1,000,000, and Eternal 1 in 10,000,000.</p></details></section>
    <section className={styles.section}><h2>Check it for yourself</h2><p>Once a discovery is confirmed, its signed result records the site, rarity draw, class, and creature seed. A creature proof also carries its individual starting traits. You can check a result, birth proof, or saved local card in your own browser. The file stays on your device.</p><ProofChecker /><details className={styles.deepDive}><summary>Try signed example results</summary><p>These examples cover the four distance bands and the Rare, Mythic, and Eternal classes. They demonstrate the calculation but are not player discoveries.</p><div className={styles.exampleLinks}><a download href="/conformance/examples/origin.json">Near home</a><a download href="/conformance/examples/wilds.json">Wilds</a><a download href="/conformance/examples/deep-wilds.json">Deep wilds</a><a download href="/conformance/examples/frontier.json">Frontier</a><a download href="/conformance/examples/rare.json">Rare</a><a download href="/conformance/examples/mythic.json">Mythic</a><a download href="/conformance/examples/eternal.json">Eternal</a><a download href="/conformance/examples/creature-proof.json">Complete creature proof</a><a download href="/conformance/examples/local-creature-card.json">Local creature card</a></div></details></section>
    <section className={styles.section}><h2>One site, one result</h2><div className={styles.featureGrid}><article><strong>Find a site</strong><p>The rules and chances are public before you travel. An undiscovered site’s creature is not published in a lookup list.</p></article><article><strong>Reveal the result</strong><p>Your confirmed encounter fixes its class and individual traits. Returning to the same site does not grant another rarity roll.</p></article><article><strong>Keep the proof</strong><p>Anyone holding the result can check it offline. An altered result fails the signature or the replayed calculation.</p></article></div></section>
    <footer className={styles.footer}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link prefetch={false} href="/creatures">Creatures</Link><Link prefetch={false} href="/about">About</Link><Link prefetch={false} href="/guide">Guide</Link></footer>
  </main>;
}
