import Link from "next/link";
import { publicPageMetadata } from "@/lib/wildz/search-metadata";
import { publicRarityTableV11, WILDS_RARITY_BANDS_V11, WILDS_RARITY_CLASSES_V11 } from "@/features/play/wilds-v11-conformance";
import ProofChecker from "./ProofChecker";
import styles from "../v11-reader.module.css";

export const metadata = publicPageMetadata("Wildz v11 Rarity Conformance — Exact Odds & Offline Proof", "All creature rarity classes, exact encounter odds by site distance, scarcity scores, and local verification of signed v11 encounter results.", "/conformance");

const BANDS = [
  { key: "origin", title: "Origin", range: "less than 25 regions", detail: "The starting region is eligible. Even here, an Eternal is possible." },
  { key: "wilds", title: "Wilds", range: "25 to under 125 regions", detail: "The site is beyond the first radial boundary." },
  { key: "deep-wilds", title: "Deep wilds", range: "125 to under 500 regions", detail: "The site lies deeper into the addressable world." },
  { key: "frontier", title: "Frontier", range: "500 regions and beyond", detail: "The highest odds apply here; travel never guarantees a class." }
] as const;
const CLASS_NAME = { trail: "Trail", uncommon: "Uncommon", rare: "Rare", mythic: "Mythic", eternal: "Eternal" } as const;
const DATA = publicRarityTableV11();

function odds(numerator: string, denominator: string) {
  return `${Number(numerator).toLocaleString("en-US")} in ${Number(denominator).toLocaleString("en-US")}`;
}

export default function ConformancePage() {
  return <main className={styles.page}>
    <nav aria-label="Site navigation" className={styles.nav}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link prefetch={false} href="/creatures">Creatures</Link><Link aria-current="page" prefetch={false} href="/conformance">Conformance</Link><Link prefetch={false} href="/">Play</Link></nav>
    <header className={styles.hero}><h1>Rarity you can verify.</h1><p>Every eligible encounter site has a chance at every class. The site’s exact distance from the starting region changes the odds. A signed result lets anyone replay the calculation after discovery.</p><Link prefetch={false} href="/creatures">How a creature becomes one of one →</Link></header>
    <section className={styles.section}><h2>Every class. Every distance.</h2><p>These are per eligible encounter result, not capture probabilities or promises after repeated attempts. Each cell comes directly from the published integer rarity law.</p><div className={styles.tableWrap}><table className={styles.odds}><thead><tr><th scope="col">Class</th>{BANDS.map(b => <th key={b.key} scope="col">{b.title}<small>{b.range}</small></th>)}</tr></thead><tbody>{WILDS_RARITY_CLASSES_V11.map(className => <tr className={styles[className]} key={className}><th scope="row">{CLASS_NAME[className]}</th>{WILDS_RARITY_BANDS_V11.map(band => { const row = DATA.find(item => item.band === band && item.className === className)!; return <td key={band}><strong>{odds(row.numerator, row.denominator)}</strong><small>{row.exactProbability} · {row.scarcityBits.toFixed(2)} bits</small></td>; })}</tr>)}</tbody></table></div><p className={styles.oddsNote}>All five class counts total 10,000,000 in each band. “1 in N” is exact only where the numerator is 1; the other cells show their exact reduced fractions.</p></section>
    <section className={styles.section}><h2>How distance works</h2><p>Let the encounter site’s signed region coordinates be <code>(x, z)</code>. The law compares <code>x² + z²</code> with <code>25²</code>, <code>125²</code>, and <code>500²</code> using integers. It measures the site, not a player’s travel history. Local offsets do not change the band.</p><div className={styles.bandGrid}>{BANDS.map(b => <article key={b.key}><h3>{b.title}</h3><small>{b.range}</small><p>{b.detail}</p></article>)}</div><p className={styles.oddsNote}>One region spans 24 world units. Frontier begins at a radial distance of 500 regions, about 12,000 world units. A circular boundary includes all directions.</p></section>
    <section className={styles.section}><h2>Scarcity is a number, not a price</h2><p>The rarity score records how surprising a class is in its band. It carries no fixed monetary value and does not predict a creature’s personality or usefulness.</p><code className={styles.formula}>scarcity bits = −log₂(class count ÷ 10,000,000)</code><p>Scores in the table are rounded to two decimals for reading; the class selection uses exact integer counts. Frontier Rare is 1 in 1,000, Mythic is 1 in 100,000, and Eternal is 1 in 1,000,000. The origin odds are 1 in 10,000, 1 in 1,000,000, and 1 in 10,000,000 respectively.</p></section>
    <section className={styles.section}><h2>Check an encounter proof</h2><p>After an admitted discovery, the encounter result contains the site address, actor, site slot, key ID, signature, exact rarity draw, class, and creature seed. Choose a result to check its Ed25519 signature and replay the law entirely in this browser.</p><ProofChecker /><p className={styles.oddsNote}>Download signed examples at each exact band boundary: <a download href="/conformance/v11/origin.json">origin</a>, <a download href="/conformance/v11/wilds.json">wilds (25)</a>, <a download href="/conformance/v11/deep-wilds.json">deep wilds (125)</a>, <a download href="/conformance/v11/frontier.json">frontier (500)</a>. Try rare-class examples: <a download href="/conformance/v11/rare.json">Rare</a>, <a download href="/conformance/v11/mythic.json">Mythic</a>, <a download href="/conformance/v11/eternal.json">Eternal</a>. These use a separate conformance-only key. They prove the math and cannot be admitted as player discoveries.</p><p className={styles.oddsNote}>The pinned public keys are part of this release. An unknown or altered key fails verification. This checker accepts v11 encounter results and labeled law examples; legacy v10 cards retain their original proof and original rarity law.</p></section>
    <section className={styles.section}><h2>What the proof means</h2><div className={styles.featureGrid}><article><strong>One site, one result</strong><p>An actor can claim one admitted result for a site slot. Returning to the same slot returns the same result rather than another rarity roll.</p></article><article><strong>Reveal after admission</strong><p>Public rules and odds are known before travel. The signed site outcome becomes inspectable after the first admitted encounter; otherwise a public lookup would turn exploration into a coordinate list.</p></article><article><strong>Signed, then replayed</strong><p>The signature commits to the actor and exact site. An unbiased draw selects the class from fixed counts. The signature also derives the creature seed. Anyone with the result can check those steps offline.</p></article></div><p>Independent outcomes never make an Eternal inevitable after a particular number of encounters. A guaranteed starter is a separate Trail grant and is excluded from this encounter odds table.</p></section>
    <footer className={styles.footer}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/world">World</Link><Link prefetch={false} href="/creatures">Creatures</Link><Link prefetch={false} href="/about">About</Link><Link prefetch={false} href="/guide">Guide</Link></footer>
  </main>;
}
