import {creationDefinitionFixture,creationContextFixture} from './creation-fixtures';
import {creationAuthorityFixture,creationSourceHead} from './creation-instance-fixtures';
import {compileCreation} from '../../src/features/play/creation/compiler';
import {emptyCreationState,type CreationState} from '../../src/features/play/creation/state';
import {sealConstructionProof} from '../../src/features/play/wilds-construction-project';
import {CREATION_CONSTRUCT_RULE_ID,CREATION_CONSTRUCT_RULE_HEAD,prepareCreationOperation,type CreationOperationContext,type CreationOperationJournal,type CreationOperationJournalRow} from '../../src/features/play/creation/operation';
export function creationOperationContextFixture():CreationOperationContext{
 const lots=Array.from({length:20},(_,i)=>sealConstructionProof({schema:'wildz.material-lot.v1' as const,lotId:`wildz:material:timber:${i.toString(16).padStart(64,'0')}`,kind:'timber' as const,quantity:1 as const,quality:1 as const,ownerReceizId:'owner',source:{sourceId:'fixture:tree',sourceHead:creationSourceHead,admittedSourceHead:creationSourceHead,kaiUPulse:1},contributors:{explorerReceizId:'owner'},authority:'source-proof-object' as const}));
 const definition=creationDefinitionFixture(),state:CreationState={...emptyCreationState(),definitions:{[definition.digest]:definition},resources:Object.fromEntries(lots.map(lot=>[lot.lotId,{id:lot.lotId,head:lot.head,kind:lot.kind,quantity:1,ownerId:'owner',spent:false}]))};
 const worker={assetId:'fixture:card',subjectId:'creature:fixture',head:creationSourceHead,proofDigest:creationSourceHead,techniques:['assembly'],ready:true,reasons:[]};
 const mandate={id:'mandate:fixture',head:creationSourceHead,workerId:worker.subjectId,ownerId:'owner',techniques:['assembly'],workCeiling:100,expiresKaiUPulse:100,revoked:false};
 const authority=creationAuthorityFixture(state),sources=[...authority.sources,{id:`rule:${CREATION_CONSTRUCT_RULE_ID}`,head:CREATION_CONSTRUCT_RULE_HEAD,kind:'rule'},{id:'space:surface',head:creationSourceHead,kind:'space'},{id:worker.subjectId,head:worker.head,kind:'creature'},{id:mandate.id,head:mandate.head,kind:'mandate'},...lots.map(lot=>({id:lot.lotId,head:lot.head,kind:'material'}))];
 return {operationId:'operation:fixture',actorId:'owner',instanceId:'instance:operation',kaiUPulse:2,definition,compileContext:creationContextFixture({budget:{timber:20},techniques:['assembly']}),state,authority:{...authority,rules:{...authority.rules,[CREATION_CONSTRUCT_RULE_ID]:CREATION_CONSTRUCT_RULE_HEAD},sources,verifySource:s=>sources.some(a=>a.id===s.id&&a.head===s.head&&a.kind===s.kind)},workers:[worker],mandates:[mandate],lots,availability:{actorId:'owner',heads:Object.fromEntries(lots.map(l=>[l.lotId,l.head])),custody:Object.fromEntries(lots.map(l=>[l.lotId,'owner'])),reserved:new Set(),spent:new Set(),stored:new Set()},workCeiling:100,causalParents:[]};
}
export function creationOperationFixture(){const context=creationOperationContextFixture(),compiled=compileCreation(context.definition,context.compileContext);if(compiled.status!=='ready')throw Error('fixture_compile_failed');return prepareCreationOperation(compiled.plan,context);}
/** Explicit deterministic journal double; browser storage qualification is separate. */
export function creationJournalFixture(){let row:CreationOperationJournalRow|null=null,failComplete=false;const journal:CreationOperationJournal={async read(){return row;},async compareAndSet(_id,expected,next){if((row?.revision??null)!==expected)return false;if(failComplete&&next.phase==='complete')throw Error('disk_failed');row=next;return true;}};return {journal,get row(){return row;},failCompletion(){failComplete=true;}};}
