import {
  BarChart3,
  Archive,
  Anchor,
  ArrowDownToLine,
  AudioWaveform,
  Bell,
  BookOpen,
  Box,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CircleHelp,
  Clipboard,
  ClipboardList,
  Code2,
  CreditCard,
  DoorClosed,
  EyeOff,
  ExternalLink,
  Footprints,
  Gamepad2,
  Gauge,
  Feather,
  Gift,
  Github,
  Globe2,
  Home,
  Hammer,
  Image,
  Layers3,
  Lamp,
  LifeBuoy,
  Lightbulb,
  LogIn,
  Lock,
  Menu,
  Map,
  Mountain,
  Package,
  Palette,
  Plane,
  Receipt,
  Radar,
  Route,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Shield,
  Shovel,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  TentTree,
  Trophy,
  Pickaxe,
  Scale,
  TreePine,
  User,
  Users,
  Waves,
  Wind,
  WalletCards,
  X
} from "lucide-react";

export const Icons = {
  archive: Archive,
  analytics: BarChart3,
  waveform: AudioWaveform,
  assets: Layers3,
  bell: Bell,
  book: BookOpen,
  box: Box,
  cart: ShoppingCart,
  camp: TentTree,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clock: Clock,
  close: X,
  code: Code2,
  collections: Box,
  copy: Clipboard,
  creditCard: CreditCard,
  docs: BookOpen,
  door: DoorClosed,
  external: ExternalLink,
  walk: Footprints,
  game: Gamepad2,
  run: Gauge,
  gift: Gift,
  github: Github,
  globe: Globe2,
  help: CircleHelp,
  home: Home,
  construction: Hammer,
  image: Image,
  lock: Lock,
  lantern: Lamp,
  enter: LogIn,
  menu: Menu,
  map: Map,
  climb: Mountain,
  flight: Plane,
  glide: Feather,
  swim: Waves,
  dive: ArrowDownToLine,
  current: Wind,
  burrow: Shovel,
  balance: Scale,
  light: Lightbulb,
  camouflage: EyeOff,
  track: Route,
  break: Hammer,
  resist: Shield,
  anchor: Anchor,
  rescue: LifeBuoy,
  orders: Receipt,
  package: Package,
  pages: ClipboardList,
  palette: Palette,
  products: ShoppingBag,
  receiz: ShieldCheck,
  pulse: Radar,
  rewards: Gift,
  search: Search,
  send: Send,
  seal: ShieldCheck,
  settings: Settings,
  sliders: SlidersHorizontal,
  sparkle: Sparkles,
  star: Star,
  store: Store,
  trophy: Trophy,
  quarry: Pickaxe,
  timber: TreePine,
  user: User,
  users: Users,
  wallet: WalletCards
};
