import type { CreationDefinition, CreationInstanceRef, CreationPose, CreationResourceBudget } from './types';
import type { CreationPlan, CreationResourceQuote } from './compiler';
import type {CreationPhaseResult} from './affordable-phase';
import {creationContainsParts} from './parts-basis';
import { validateCreationBudget } from './resources';
import {validConstructionHead,validConstructionId} from '../wilds-construction-project';
import { creationPlacementMessage } from './placement-message';
export type CreationConversationState=Readonly<{ownerId:string;spaceId:string;open:boolean;minimized:boolean;workerIds:readonly string[];budget:CreationResourceBudget;budgetMode:'automatic'|'manual';quote:CreationResourceQuote|null;targetDefinition:CreationDefinition|null;targetQuote:CreationResourceQuote|null;draft:string;history:readonly {role:'user'|'assistant';text:string}[];requestId:string|null;definition:CreationDefinition|null;selectedDefinition:CreationDefinition|null;instance:CreationInstanceRef|null;plan:CreationPlan|null;placement:CreationPose;status:'idle'|'planning'|'preview'|'committing'|'recovering'|'blocked';reason:string|null;operationId:string|null}>;
export type CreationConversationEvent={type:'environment';ownerId:string;spaceId:string}|{type:'open'|'close'|'minimize'|'invalidate'}|{type:'draft'|'starter';text:string}|{type:'selection';definition:CreationDefinition|null;instance?:CreationInstanceRef|null;pose?:CreationPose;workerIds?:readonly string[];budget?:CreationResourceBudget}|{type:'phase'|'full-design'}|{type:'target';definition:CreationDefinition}|{type:'phase-ready';requestId:string;phase:Extract<CreationPhaseResult,{status:'ready'}>}|{type:'workers';ids:readonly string[]}|{type:'budget';budget:CreationResourceBudget;mode?:'automatic'|'manual'}|{type:'quote';requestId:string;quote:CreationResourceQuote;budget?:CreationResourceBudget}|{type:'placement';pose:CreationPose}|{type:'request'|'compile-request';requestId:string}|{type:'proposal';requestId:string;definition:CreationDefinition;reply:string}|{type:'compiled';requestId:string;plan:CreationPlan;minimize?:boolean}|{type:'blocked';requestId?:string;reason:string}|{type:'commit'}|{type:'admitted';instance:CreationInstanceRef}|{type:'unknown';operationId:string};
export function initialCreationConversation(ownerId:string,spaceId:string,pose:CreationPose):CreationConversationState {return {ownerId,spaceId,open:false,minimized:false,workerIds:[],budget:{hay:0,timber:0,stone:0},budgetMode:'automatic',quote:null,targetDefinition:null,targetQuote:null,draft:'',history:[],requestId:null,definition:null,selectedDefinition:null,instance:null,plan:null,placement:pose,status:'idle',reason:null,operationId:null};}
export function reduceCreationConversation(state:CreationConversationState,event:CreationConversationEvent):CreationConversationState {
 const invalidate={requestId:null,plan:null,quote:null,status:'idle' as const,reason:null};
 if(event.type==='starter')return state.draft||state.history.length||state.definition||state.instance||state.operationId||state.status!=='idle'?state:{...state,draft:event.text.slice(0,4000)};
 if(event.type==='environment'){if(event.ownerId===state.ownerId&&event.spaceId===state.spaceId)return state;return {...initialCreationConversation(event.ownerId,event.spaceId,state.placement),open:state.open};}
 if(event.type==='invalidate')return ['committing','recovering'].includes(state.status)?state:{...state,...invalidate};
 if(event.type==='close')return {...state,open:false,minimized:false,...(state.status==='planning'?invalidate:{})};
 if(event.type==='open')return {...state,open:true,minimized:false};
 if(event.type==='minimize')return {...state,minimized:!state.minimized};
 if(event.type==='draft')return {...state,draft:event.text.slice(0,4000)};
 if(event.type==='unknown')return {...state,status:'recovering',minimized:false,operationId:event.operationId,reason:'Checking the existing build outcome. Resources remain reserved.'};
 if(state.status==='recovering'||state.status==='committing'){
  if(event.type==='admitted'){const built=state.definition,target=state.targetDefinition&&state.targetDefinition.digest!==built?.digest?state.targetDefinition:null;return {...state,status:'idle',minimized:false,instance:{instanceId:event.instance.instanceId,head:event.instance.head,definitionDigest:event.instance.definitionDigest},operationId:null,reason:target?'Section built and saved. The full design is ready for the next materials.':'Built and saved in the world.',requestId:null,plan:null,quote:null,definition:target||built,selectedDefinition:built,targetDefinition:target,targetQuote:null};}
  if(event.type==='blocked')return {...state,status:'blocked',minimized:false,reason:creationPlacementMessage(event.reason)};
  return state;
 }
 if(event.type==='phase'||event.type==='full-design')return state.definition?{...state,...invalidate,definition:state.targetDefinition||state.definition,targetDefinition:null,targetQuote:null}:state;
 if(event.type==='target')return state.definition&&creationContainsParts(event.definition,state.definition)?{...state,targetDefinition:event.definition}:state;
 if(event.type==='phase-ready'){const target=state.targetDefinition||state.definition;if(state.status!=='planning'||event.requestId!==state.requestId||!target||!creationContainsParts(target,event.phase.definition)||event.phase.plan.definitionDigest!==event.phase.definition.digest)return state;try{validateCreationBudget(event.phase.budget);}catch{return state;}return {...state,targetDefinition:target,targetQuote:event.phase.targetQuote,definition:event.phase.definition,quote:{definitionDigest:event.phase.definition.digest,requiredResources:event.phase.plan.requiredResources,requiredWork:event.phase.plan.requiredWork},budget:event.phase.budget,plan:event.phase.plan,placement:event.phase.plan.pose,status:'preview',draft:'',reason:null};}
 if(event.type==='selection'){if(event.workerIds&&(event.workerIds.length>32||!event.workerIds.every(validConstructionId)))return state;if(event.budget){try{validateCreationBudget(event.budget);}catch{return state;}}if(event.pose&&![event.pose.position?.x,event.pose.position?.y,event.pose.position?.z,event.pose.yaw].every(n=>Number.isFinite(n)&&Math.abs(n!)<=1e9))return state;if(event.instance&&(!event.definition||!validConstructionId(event.instance.instanceId)||!validConstructionHead(event.instance.head)||event.instance.definitionDigest!==event.definition.digest)||event.definition&&event.definition.creatorId!==state.ownerId&&!event.instance)return state;return {...state,...invalidate,definition:event.definition,targetDefinition:null,targetQuote:null,selectedDefinition:event.instance?event.definition:null,instance:event.instance||null,placement:event.pose||state.placement,workerIds:event.workerIds?[...new Set(event.workerIds)]:state.workerIds,budget:state.budgetMode==='manual'?state.budget:event.budget||state.budget,history:[]};}
 if(event.type==='workers')return {...state,...invalidate,workerIds:[...new Set(event.ids)]};
 if(event.type==='budget'){try{validateCreationBudget(event.budget);}catch{return state;}return {...state,...invalidate,budget:event.budget,budgetMode:event.mode||'manual'};}
 if(event.type==='quote'){if(event.requestId!==state.requestId||state.status!=='planning'||event.quote.definitionDigest!==state.definition?.digest)return state;try{validateCreationBudget(event.quote.requiredResources);if(event.budget)validateCreationBudget(event.budget);}catch{return state;}return {...state,quote:event.quote,...(event.budget?{budget:state.budgetMode==='automatic'?event.budget:Object.fromEntries(Object.entries(state.budget).map(([kind,amount])=>[kind,Math.min(amount,event.budget![kind]||0)]))}:{})};}
 if(event.type==='placement')return {...state,...invalidate,plan:state.plan,placement:event.pose};
 if(event.type==='compile-request')return {...state,requestId:event.requestId,status:'planning',quote:null,reason:null};
 if(event.type==='request')return {...state,requestId:event.requestId,status:'planning',plan:null,quote:null,reason:null,history:[...state.history,{role:'user',text:state.draft}].slice(-40) as CreationConversationState['history']};
 if(event.type==='proposal'){if(event.requestId!==state.requestId||state.status!=='planning'||event.definition.creatorId!==(state.instance?state.definition?.creatorId:state.ownerId))return state;return {...state,definition:event.definition,targetDefinition:null,targetQuote:null,history:[...state.history,{role:'assistant',text:event.reply}].slice(-40) as CreationConversationState['history']};}
 if(event.type==='compiled'){if(event.requestId!==state.requestId||event.plan.definitionDigest!==state.definition?.digest)return state;return {...state,quote:{definitionDigest:event.plan.definitionDigest,requiredResources:event.plan.requiredResources,requiredWork:event.plan.requiredWork},plan:event.plan,placement:event.plan.pose,status:'preview',draft:'',minimized:event.minimize?true:state.minimized};}
 if(event.type==='blocked'){if(event.requestId&&event.requestId!==state.requestId)return state;return {...state,status:'blocked',minimized:false,reason:creationPlacementMessage(event.reason)};}
 if(event.type==='commit')return state.plan?{...state,status:'committing',reason:null}:state;
 return state;
}
