import type {CreationPhysicalProjection} from './projection';
import type {CreationPoint} from './types';
import type {CreationSolid,CreationSurface} from './geometry';
const CELL=16,STEP=.26,HEIGHT=1.55;
type Entry<T>=Readonly<{instanceId:string;value:T}>;
type SpaceIndex=Readonly<{solids:Map<string,Entry<CreationSolid>[]>;surfaces:Map<string,Entry<CreationSurface>[]>}>;
export type CreationNavigation=Readonly<{instanceCount:number;spaces:ReadonlyMap<string,SpaceIndex>}>;
const key=(x:number,z:number)=>`${Math.floor(x/CELL)}:${Math.floor(z/CELL)}`;
function insert<T extends CreationSolid|CreationSurface>(map:Map<string,Entry<T>[]>,entry:Entry<T>){const v=entry.value,c=Math.abs(Math.cos(v.yaw)),s=Math.abs(Math.sin(v.yaw)),x=c*v.halfExtents.x+s*v.halfExtents.z+.5,z=s*v.halfExtents.x+c*v.halfExtents.z+.5;const minX=Math.floor((v.center.x-x)/CELL),maxX=Math.floor((v.center.x+x)/CELL),minZ=Math.floor((v.center.z-z)/CELL),maxZ=Math.floor((v.center.z+z)/CELL);if((maxX-minX+1)*(maxZ-minZ+1)>4096)throw Error('creation_navigation_residency_required');for(let ix=minX;ix<=maxX;ix++)for(let iz=minZ;iz<=maxZ;iz++){const k=`${ix}:${iz}`,bucket=map.get(k)||[];bucket.push(entry);map.set(k,bucket);}}
export function prepareCreationNavigation(projections:readonly CreationPhysicalProjection[]):CreationNavigation{const instances=new Map<string,string>(),spaces=new Map<string,SpaceIndex>();for(const p of projections){const previous=instances.get(p.instanceId);if(previous){if(previous!==p.head)throw Error('creation_projection_head_conflict');continue;}instances.set(p.instanceId,p.head);const index=spaces.get(p.spaceId)||{solids:new Map(),surfaces:new Map()};p.solids.forEach(value=>insert(index.solids,{instanceId:p.instanceId,value}));p.walkable.forEach(value=>insert(index.surfaces,{instanceId:p.instanceId,value}));spaces.set(p.spaceId,index);}return {instanceCount:instances.size,spaces};}
function local(v:CreationSolid|CreationSurface,p:CreationPoint){const x=p.x-v.center.x,z=p.z-v.center.z,c=Math.cos(v.yaw),s=Math.sin(v.yaw);return {x:x*c-z*s,z:x*s+z*c};}
function floor(index:SpaceIndex,p:CreationPoint){let y=p.y;for(const {value:s} of index.surfaces.get(key(p.x,p.z))||[]){const q=local(s,p);if(Math.abs(q.x)<=s.halfExtents.x&&Math.abs(q.z)<=s.halfExtents.z&&s.center.y<=p.y+STEP&&s.center.y>=p.y-STEP)y=Math.max(y,s.center.y);}return y;}
function blocked(index:SpaceIndex,p:CreationPoint,radius:number){return (index.solids.get(key(p.x,p.z))||[]).some(({value:s})=>{if(p.y>=s.center.y+s.halfExtents.y-.00001||p.y+HEIGHT<=s.center.y-s.halfExtents.y+.00001)return false;const q=local(s,p);return Math.abs(q.x)<s.halfExtents.x+radius&&Math.abs(q.z)<s.halfExtents.z+radius;});}
export function resolveCreationMovement(runtime:CreationNavigation,spaceId:string,from:CreationPoint,to:CreationPoint,radius=.35){if(![from.x,from.y,from.z,to.x,to.y,to.z,radius].every(Number.isFinite)||radius<0||radius>.5)throw Error('creation_movement_invalid');const index=runtime.spaces.get(spaceId);if(!index)return {position:to,blocked:false};const distance=Math.hypot(to.x-from.x,to.z-from.z),steps=Math.max(1,Math.ceil(distance/.08));if(steps>256)return {position:from,blocked:true};let position=from;for(let i=1;i<=steps;i++){const next={x:from.x+(to.x-from.x)*i/steps,y:position.y,z:from.z+(to.z-from.z)*i/steps};next.y=floor(index,next);if(blocked(index,next,radius))return {position,blocked:true};position=next;}return {position,blocked:false};}
export function findCreationRoute(runtime:CreationNavigation,spaceId:string,from:CreationPoint,to:CreationPoint){const index=runtime.spaces.get(spaceId);if(!index)return {reachable:false,points:[] as CreationPoint[]};const surfaces=[...new Map([...index.surfaces.values()].flat().map(e=>[`${e.instanceId}:${e.value.id}`,e.value])).values()];if(surfaces.length>2048)return {reachable:false,points:[] as CreationPoint[]};const nearest=(p:CreationPoint)=>surfaces.findIndex(s=>Math.hypot(s.center.x-p.x,s.center.y-p.y,s.center.z-p.z)<.01),start=nearest(from),end=nearest(to),previous=new Map<number,number>();if(start<0||end<0)return {reachable:false,points:[] as CreationPoint[]};const queue=[start];previous.set(start,-1);for(let cursor=0;cursor<queue.length&&!previous.has(end);cursor++){const a=surfaces[queue[cursor]];for(let j=0;j<surfaces.length;j++){if(previous.has(j))continue;const b=surfaces[j],point=b.center,q=local(a,point);if(Math.abs(a.center.y-b.center.y)>STEP||Math.abs(q.x)>a.halfExtents.x+b.halfExtents.x||Math.abs(q.z)>a.halfExtents.z+b.halfExtents.z)continue;const midpoint={x:(a.center.x+b.center.x)/2,y:Math.max(a.center.y,b.center.y),z:(a.center.z+b.center.z)/2};if(blocked(index,midpoint,.2))continue;previous.set(j,queue[cursor]);queue.push(j);}}if(!previous.has(end))return {reachable:false,points:[] as CreationPoint[]};const points:CreationPoint[]=[];for(let i=end;i>=0;i=previous.get(i)!)points.unshift(surfaces[i].center);return {reachable:true,points};}
