'use client';
import {useState,type SyntheticEvent} from 'react';
import {editCreationBudget} from './preview-budget';
import { FarmBuilderControls } from './FarmBuilderControls';
import type { FarmLayoutOptions } from './farm-layout';
import {CreationLibraryControls} from './CreationLibraryControls';
import type {CreationObjectLibraryInput} from './library-session';
import type {CreationDefinition} from './types';
import type {CreationInstance} from './instance';
import { usePanelPosition } from './use-panel-position';
import { GripHorizontal } from 'lucide-react';
import { WildsCreatureThumbnail } from '../WildsCreatureThumbnail';
import { Box, Hammer, Minus, Mountain, RotateCw, Send, Sparkles, Tractor, Trees, Users, Wheat, X } from 'lucide-react';
import type { CreationConversationState, CreationConversationEvent } from './conversation';
import type { CreationWorker } from './capabilities';
import type { PortableCardAsset } from '../portable-card';
import { isCreationPlacementCollision } from './placement-message';
export type CreationPanelObject=Readonly<{definition:CreationDefinition;instance:CreationInstance}>;
export type CreationPanelProps={onGatherHay?:()=>void;onCreateFarm?:(options:FarmLayoutOptions)=>void;onSaveObject?:(instanceId:string)=>Promise<void>;objectLibrary?:CreationObjectLibraryInput;objects?:readonly CreationPanelObject[];state:CreationConversationState;workers:readonly CreationWorker[];cards:readonly PortableCardAsset[];materialCounts:Record<string,number>;onChange:(e:CreationConversationEvent)=>void;onAsk:()=>void;onBuild:()=>void;onClose:()=>void;onManualBuild:()=>void;canBuild:boolean;classes?:Record<string,string>};
export function CreationBudgetInput({kind,amount,owned,disabled,onChange}:{kind:string;amount:number;owned:number;disabled:boolean;onChange:(amount:number)=>void}){
 const [editing,setEditing]=useState<string|null>(null);
 return <input aria-label={`${kind} resource budget`} disabled={disabled} type="text" inputMode="numeric" value={editing??String(amount)} onFocus={()=>setEditing(String(amount))} onBlur={()=>setEditing(null)} onChange={event=>{const next=editCreationBudget(event.target.value,owned);if(!next)return;setEditing(next.text);onChange(next.amount);}}/>;
}
export function WildsCreationPanel({onGatherHay,onCreateFarm,onSaveObject,objectLibrary,objects=[],state,workers,cards,materialCounts,onChange,onAsk,onBuild,onClose,onManualBuild,canBuild,classes={}}:CreationPanelProps){
 const panelPosition=usePanelPosition();
 const [objectsOpen,setObjectsOpen]=useState(false);
 const [savingObject,setSavingObject]=useState<string|null>(null);
 const [saveMessage,setSaveMessage]=useState('');
 const saveObject=async(id:string)=>{if(!onSaveObject||savingObject)return;setSavingObject(id);setSaveMessage('Preparing your verified creation image…');try{await onSaveObject(id);setSaveMessage('Saved to your account library and downloaded.');}catch(error){setSaveMessage(error instanceof Error?error.message:'The creation image could not be saved.');}finally{setSavingObject(null);}};
 const onMenuToggle=(event:SyntheticEvent<HTMLDetailsElement>)=>{const opened=event.currentTarget;if(opened.open)opened.parentElement?.querySelectorAll('details').forEach(menu=>{if(menu!==opened)menu.open=false;});};
 const resourceCount=Object.values(state.budget).reduce((total,n)=>total+n,0);
 const c=(key:string)=>classes[key]||`creation-${key}`,busy=['planning','committing','recovering'].includes(state.status);
 const menuHeading=(title:string,description:string)=><div className={c('menuHeading')}><strong>{title}</strong><small>{description}</small></div>;
 if(state.minimized)return <button className={c('minimized')} onClick={()=>onChange({type:'minimize'})} aria-label="Expand creation conversation" title="Open creation conversation"><Sparkles size={18}/></button>;
 return <section ref={panelPosition.ref} style={panelPosition.style} className={c('panel')} aria-label="Create with creatures" onKeyDown={event=>event.stopPropagation()}>
  <header className={c('header')}><button className={c('dragHandle')} type="button" aria-label="Move creation panel" title="Drag to move. Arrow keys move the panel; Home resets it." {...panelPosition.handle}><GripHorizontal size={16}/><Sparkles size={17}/><strong>Create</strong></button><div><button type="button" aria-label="Minimize creation conversation" onClick={()=>onChange({type:'minimize'})}><Minus size={17}/></button><button type="button" aria-label="Close creation conversation" onClick={onClose}><X size={18}/></button></div></header>
  <div className={c('body')}>
   {state.history.length?<div className={c('history')} aria-live="polite">{state.history.slice(-6).map((item,i)=><p key={`${i}:${item.role}`} data-speaker={item.role}>{item.text}</p>)}</div>:<div className={c('welcome')}><p>What would you like to build?</p><small>Start with a home and bed. Or create anything you imagine.</small></div>}
   <div className={c('menus')} data-has-farm={onCreateFarm ? 'true' : undefined}>
    <details onToggle={onMenuToggle}><summary aria-label="Choose creatures" title="Choose creatures"><Users size={17}/>{state.workerIds.length?<span data-count className={c('menuCount')} aria-label={`${state.workerIds.length} creatures selected`}>{state.workerIds.length}</span>:null}<span>Creatures</span></summary><div className={c('roster')}>{menuHeading('Creature crew','Choose who will build with you.')}{workers.map(worker=>{const card=cards.find(card=>card.id===worker.assetId);return <button type="button" key={worker.assetId} disabled={!worker.ready||busy} aria-pressed={state.workerIds.includes(worker.assetId)} title={worker.reasons.join(' ')||worker.techniques.join(' · ')} onClick={()=>onChange({type:'workers',ids:state.workerIds.includes(worker.assetId)?state.workerIds.filter(id=>id!==worker.assetId):[...state.workerIds,worker.assetId]})}><span className={c('portrait')} aria-hidden="true">{card?<WildsCreatureThumbnail asset={card}/>: '✦'}</span><span>{card?.manifest.name||'Companion'}<small>{worker.ready?worker.techniques.join(' · '):'Needs care'}</small></span></button>;})}{!workers.length?<small>No current creatures are available.</small>:null}</div></details>
    <details onToggle={onMenuToggle}><summary aria-label="Allocate resources" title="Allocate resources"><Wheat size={17}/>{resourceCount?<span data-count className={c('menuCount')} aria-label={`${resourceCount} resource units allocated`}>{resourceCount}</span>:null}<span>Resources</span></summary><div className={c('resources')}>{menuHeading('Material reserve','Set how much your crew can use.')}{onGatherHay?<button className={c('gatherHay')} type="button" disabled={busy} onClick={()=>{onChange({type:'minimize'});onGatherHay();}}><Wheat size={18}/><span>Gather hay<small>Find a patch · collect within reach</small></span></button>:null}{['hay','timber','stone'].map(kind=><label key={kind}><span className={c('materialIcon')} aria-hidden="true">{kind==='hay'?<Wheat size={18}/>:kind==='timber'?<Trees size={18}/>:<Mountain size={18}/>}</span><span>{kind}<small>{materialCounts[kind]||0} carried</small></span><CreationBudgetInput kind={kind} disabled={['committing','recovering'].includes(state.status)} owned={materialCounts[kind]||0} amount={state.budget[kind]||0} onChange={amount=>onChange({type:'budget',budget:{...state.budget,[kind]:amount}})}/></label>)}{state.budgetMode==='manual'?<button type="button" disabled={busy} onClick={()=>onChange({type:'budget',budget:state.budget,mode:'automatic'})}>Use automatic allocation</button>:<small>Automatically allocate the quoted cost, up to what you carry.</small>}</div></details>
    <details onToggle={event=>{onMenuToggle(event);setObjectsOpen(event.currentTarget.open);}}><summary aria-label="Choose object" title="Choose object"><Box size={17}/>{state.definition?<span data-count className={c('menuCount')} aria-label={state.instance?"1 placed creation selected":"1 draft selected"}>1</span>:null}<span>Objects</span></summary><div className={c('objects')}>{menuHeading('Your creations','Select, import or refine a creation.')}{objectLibrary?<CreationLibraryControls library={objectLibrary} active={objectsOpen} busy={busy} selectedId={state.instance?.instanceId} onChange={onChange}/>:null}{objects.filter(object=>object.instance.ownerId===state.ownerId&&object.instance.spaceId===state.spaceId).map((object,index)=><div key={object.instance.instanceId} data-placed-object><button type="button" disabled={busy} aria-pressed={state.instance?.instanceId===object.instance.instanceId} onClick={()=>onChange({type:'selection',definition:object.definition,pose:object.instance.pose,instance:{instanceId:object.instance.instanceId,head:object.instance.head,definitionDigest:object.instance.definitionDigest}})}>Creation {index+1}<small>{object.definition.nodes.length} parts · {Object.values(object.instance.nodeStates).some(n=>n.kind==='equipment')?'equipment':Object.values(object.instance.nodeStates).some(n=>n.kind==='garden')?'garden':'place'}</small></button>{onSaveObject?<button type="button" disabled={busy||Boolean(savingObject)} onClick={()=>void saveObject(object.instance.instanceId)}>{savingObject===object.instance.instanceId?'Saving…':'Save proof image'}</button>:null}</div>)}{saveMessage?<p role="status">{saveMessage}</p>:null}{state.definition?<><small>{state.instance?'Selected built creation':'Unbuilt draft'} · {state.definition.nodes.length} parts</small><button type="button" aria-pressed={state.status==='preview'} disabled={busy} onClick={()=>onChange({type:'workers',ids:state.workerIds})}>{state.instance?'Prepare changes':'Place this draft'}</button></>:<small>Select a creation to change it with a prompt.</small>}<button type="button" disabled={busy||!state.definition} onClick={()=>onChange({type:'selection',definition:null})}>Start a new creation</button></div></details>
    {onCreateFarm?<details onToggle={onMenuToggle}><summary aria-label="Build a farm" title="Build a farm"><Tractor size={17}/><span>Farm</span></summary><FarmBuilderControls busy={busy} onCreate={onCreateFarm}/></details>:null}
    <button className={c('manual')} type="button" aria-label="Manual building" title="Open building pieces" onClick={onManualBuild}><Hammer size={15}/></button>
   </div>
   {state.definition?<small className={c('binding')}>{state.instance?'Changes apply to your selected creation.':'Build here adds this draft to the world.'}</small>:null}
   {state.quote||state.targetDefinition&&state.definition?.digest!==state.targetDefinition.digest?<div className={c('costs')} tabIndex={0} role="region" aria-label="Construction costs">
   {state.targetDefinition&&state.definition?.digest!==state.targetDefinition.digest?<div className={c('status')} aria-label="Saved construction goal"><strong>Build this section now</strong><p>{state.definition?.nodes.length} of {state.targetDefinition.nodes.length} planned parts. The complete design is saved for expansion.</p>{state.targetQuote?<small>Full remaining design before this section: {Object.entries(state.targetQuote.requiredResources).map(([kind,n])=>`${n} ${kind}`).join(' · ')}.</small>:null}<button type="button" disabled={busy} onClick={()=>onChange({type:'full-design'})}>Preview full design</button></div>:null}
   {state.quote?<div className={c('status')} aria-label="Creation material quote"><strong>{state.targetDefinition&&state.definition?.digest!==state.targetDefinition.digest?'This section’s cost':state.instance&&state.targetDefinition?'Remaining design cost':'Full design cost'}</strong>{Object.entries(state.quote.requiredResources).map(([kind,need])=>{const have=materialCounts[kind]||0,allocated=state.budget[kind]||0;return <p key={kind}>{kind}: need {need} · have {have} · missing {Math.max(0,need-have)} · allocated {allocated}{state.budgetMode==='manual'&&allocated<need?` · allocation short by ${need-allocated}`:''}</p>;})}<small>{state.budgetMode==='automatic'?'Materials allocated automatically up to what you carry.':'Your chosen allocation limit is preserved.'} The full design stays saved.</small></div>:null}
   </div>:null}
   {state.status==='planning'?<p role="status" className={c('status')}>Your creatures are considering the design…</p>:null}
   {state.reason?<p role="status" className={c('status')}>{state.reason}</p>:null}
   {state.definition&&!state.instance&&state.status==='blocked'&&isCreationPlacementCollision(state.reason)?<div className={c('status')}><button type="button" onClick={()=>onChange({type:'minimize'})}>Move full draft</button><small>Tap clear ground to move the preview, then choose Build here.</small></div>:null}
   {state.definition&&state.definition.digest!==state.selectedDefinition?.digest&&state.status==='blocked'&&!state.operationId&&!isCreationPlacementCollision(state.reason)?<button type="button" disabled={!state.workerIds.length} onClick={()=>onChange({type:'phase'})}>{state.instance?'Preview next affordable section':'Preview affordable first section'}</button>:null}
   <div className={c('composerArea')}><form className={c('composer')} onSubmit={event=>{event.preventDefault();onAsk();}}><textarea aria-label="Creation prompt" placeholder={state.definition?'Tell your creatures what to change…':'Tell your creatures what to build…'} maxLength={4000} rows={3} disabled={busy} value={state.draft} onChange={event=>onChange({type:'draft',text:event.target.value})}/><button type="submit" disabled={busy||!state.draft.trim()||!state.workerIds.length} aria-label="Send creation prompt"><Send size={17}/></button></form></div>
   {state.status==='preview'?<div className={c('previewActions')}><div><small>Preview · {Object.entries(state.plan?.requiredResources||{}).map(([kind,n])=>`${n} ${kind}`).join(' · ')}</small><button type="button" aria-label="Rotate creation" onClick={()=>onChange({type:'placement',pose:{...state.placement,yaw:state.placement.yaw+Math.PI/2}})}><RotateCw size={17}/></button></div><button type="button" disabled={!canBuild} onClick={onBuild}>{state.targetDefinition&&state.definition?.digest!==state.targetDefinition.digest?'Build this section':'Build here'}</button>{!canBuild?<small>Live construction is awaiting authenticated world admission.</small>:null}</div>:null}
  </div>
 </section>;
}
