import Link from "next/link";
import { publicPageMetadata } from "@/lib/wildz/search-metadata";
import styles from "../v11-reader.module.css";

export const metadata = publicPageMetadata("The Wildz World — An Open-Ended Addressable Map", "Explore how Wildz v11 names places with exact region addresses, builds terrain nearby, and measures distance for creature discovery.", "/world");

const AXES = [
  ["World version", "The address declares its rule set. A v11 address is interpreted by v11 generation and movement rules."],
  ["Region X and Z", "Signed decimal integers name a region in any direction from the origin. Their digits are handled exactly, not squeezed into floating point coordinates."],
  ["Local X and Z", "Integer millionths of a world unit locate a point within its 24 × 24 unit region. An offset always stays between 0 and 24 million."],
] as const;

export default function WorldPage() {
  return <main className={styles.page}>
    <nav aria-label="Site navigation" className={styles.nav}><Link prefetch={false} href="/">Wildz</Link><Link aria-current="page" prefetch={false} href="/world">World</Link><Link prefetch={false} href="/creatures">Creatures</Link><Link prefetch={false} href="/conformance">Conformance</Link><Link prefetch={false} href="/">Play</Link></nav>
    <header className={styles.hero}><h1>A world without a drawn edge.</h1><p>Wildz v11 gives places exact addresses instead of drawing one enormous map into memory. Wherever you travel, the nearby world is built around you. The address remains the same when you return.</p><Link prefetch={false} href="/conformance">See how location changes rarity →</Link></header>
    <section className={styles.section}><h2>One place, one address</h2><p className={styles.lede}>A place has a region and a position inside it. One region spans 24 × 24 world units; its local position is measured to one millionth of a unit.</p><code className={styles.formula}>{`{ worldVersion: 11, regionX: "-3", regionZ: "42", localX: 12000000, localZ: 6000000 }`}</code><p>The example means a point halfway across region X −3 and one quarter across region Z 42. Whole-region movement carries the local offset into the neighboring address without rounding away the location.</p><dl>{AXES.map(([term, definition]) => <div className={styles.factLine} key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section>
    <section className={styles.section}><h2>How large is it?</h2><p>The region grid has no designed outer border. Signed region integers can keep growing in all directions. This makes the map open-ended at the address level, with faraway regions generated when needed instead of stored in advance.</p><div className={styles.featureGrid}><article><strong>24 units</strong><p>Width and length of a single encounter region.</p></article><article><strong>500 regions</strong><p>Radial threshold where the frontier rarity band begins, about 12,000 world units from the origin.</p></article><article><strong>Nearby only</strong><p>Rendering, movement, and active simulation use bounded local numbers and a limited active window.</p></article></div><p>There is no finite number of prepainted tiles to exhaust. Real devices and servers remain finite: address parsing has a 4,096 digit safety limit per region coordinate, and only nearby terrain can be kept active at once. “Open-ended” describes the design of the address space, not unlimited simultaneous rendering or storage.</p></section>
    <section className={styles.section}><h2>How a region takes shape</h2><p>Terrain is sampled from the exact region address plus local position. The same address feeds a deterministic terrain result, so returning to a place recovers its underlying shape. Nearby patches are meshed at bounded detail and can shift their local origin as the camera travels, keeping huge global coordinates out of the renderer.</p><p>Terrain, biome cues, encounter ecology, and live world changes serve different roles. Deterministic generation supplies a stable starting place; admitted play can add history that generation alone would never know. A discovered site is part of a lived world, not simply a random pixel on a map.</p><div className={styles.callout}><strong>A coordinate carries distance</strong><p>For rarity, the game compares <code>regionX² + regionZ²</code> to exact radial thresholds of <code>25²</code>, <code>125²</code>, and <code>500²</code>. The site’s location sets its band. Every band keeps a chance at Rare, Mythic, and Eternal.</p></div></section>
    <section className={styles.section}><h2>A return has meaning</h2><p>A saved v10 location keeps its world-unit meaning when it is mapped into a v11 address. A creature’s verified first meeting place can also become a place to revisit. The world remembers what happened through proof and history rather than changing the underlying terrain seed.</p><p>Travel far enough and your coordinates may be enormous; the ground beneath your feet is still described by a small local position. That is how the world can keep offering directions while the frame stays practical for a browser.</p><Link prefetch={false} href="/creatures">Meet the creatures who live in it →</Link></section>
    <footer className={styles.footer}><Link prefetch={false} href="/">Wildz</Link><Link prefetch={false} href="/creatures">Creatures</Link><Link prefetch={false} href="/conformance">Conformance</Link><Link prefetch={false} href="/about">About</Link><Link prefetch={false} href="/guide">Guide</Link></footer>
  </main>;
}
