import {KAI_N_DAY_MICRO} from './kai-klok-moment';
export const PLAYER_BREATHS_PER_DAY=17491;
export const PLAYER_BREATH_CAPACITY_MICRO=PLAYER_BREATHS_PER_DAY*1_000_000;
const DENOMINATOR=KAI_N_DAY_MICRO*20n;
export type PlayerBreaths=Readonly<{schema:'wildz.player-breaths.v1';clockRooted:boolean;reserveMicroBreaths:number;spentMicroBreaths:number;restoredMicroBreaths:number;spentTodayMicroBreaths:number;lastKaiUPulse:number;day:number;mode:'active'|'camp'|'bed'|'swim'|'flight'|'glide';timeRemainder:string}>;
function validKai(value:number){return Number.isSafeInteger(value)&&value>=0;}
function integer(value:unknown,max=Number.MAX_SAFE_INTEGER):value is number{return Number.isSafeInteger(value)&&Number(value)>=0&&Number(value)<=max;}
export function isPlayerBreaths(value:unknown):value is PlayerBreaths{if(!value||typeof value!=='object'||Array.isArray(value))return false;const s=value as PlayerBreaths;try{return s.schema==='wildz.player-breaths.v1'&&typeof s.clockRooted==='boolean'&&Object.keys(s).sort().join(',')==='clockRooted,day,lastKaiUPulse,mode,reserveMicroBreaths,restoredMicroBreaths,schema,spentMicroBreaths,spentTodayMicroBreaths,timeRemainder'&&integer(s.reserveMicroBreaths,PLAYER_BREATH_CAPACITY_MICRO)&&integer(s.spentMicroBreaths)&&integer(s.restoredMicroBreaths)&&integer(s.spentTodayMicroBreaths)&&validKai(s.lastKaiUPulse)&&s.day===Number(BigInt(s.lastKaiUPulse)/KAI_N_DAY_MICRO)&&['active','camp','bed','swim','flight','glide'].includes(s.mode)&&typeof s.timeRemainder==='string'&&/^-?(0|[1-9][0-9]{0,12})$/.test(s.timeRemainder)&&BigInt(s.timeRemainder)>-DENOMINATOR&&BigInt(s.timeRemainder)<DENOMINATOR;}catch{return false;}}
export function createPlayerBreaths(kaiUPulse:number,legacyEnergy=100,clockRooted=true):PlayerBreaths{if(!validKai(kaiUPulse))throw Error('player_breath_time_invalid');const percent=Number.isFinite(legacyEnergy)?Math.max(0,Math.min(100,legacyEnergy)):84;return {schema:'wildz.player-breaths.v1',clockRooted,reserveMicroBreaths:Math.round(PLAYER_BREATH_CAPACITY_MICRO*percent/100),spentMicroBreaths:0,restoredMicroBreaths:0,spentTodayMicroBreaths:0,lastKaiUPulse:kaiUPulse,day:Number(BigInt(kaiUPulse)/KAI_N_DAY_MICRO),mode:'active',timeRemainder:'0'};}
export function restorePlayerBreaths(value:unknown,kaiUPulse:number,legacyEnergy=84):PlayerBreaths{return isPlayerBreaths(value)?value:createPlayerBreaths(kaiUPulse,legacyEnergy);}
export function advancePlayerBreaths(state:PlayerBreaths,kaiUPulse:number,mode:PlayerBreaths['mode']=state.mode,clockRooted=true):PlayerBreaths{
 if(!isPlayerBreaths(state)||!validKai(kaiUPulse)||!['active','camp','bed','swim','flight','glide'].includes(mode))throw Error('player_breath_state_invalid');if(!state.clockRooted&&clockRooted)return {...state,clockRooted:true,lastKaiUPulse:kaiUPulse,day:Number(BigInt(kaiUPulse)/KAI_N_DAY_MICRO),mode,timeRemainder:'0'};if(kaiUPulse<state.lastKaiUPulse)return state;if(kaiUPulse===state.lastKaiUPulse&&mode===state.mode)return state;
 // All modes share a denominator. Fractional work survives both tick splitting and mode changes.
 const rate=state.mode==='bed'?240n:state.mode==='camp'?160n:state.mode==='swim'?-60n:state.mode==='flight'?-20n:state.mode==='glide'?-8n:-1n;
 const numerator=BigInt(kaiUPulse-state.lastKaiUPulse)*BigInt(PLAYER_BREATH_CAPACITY_MICRO)*rate+BigInt(state.timeRemainder),change=numerator/DENOMINATOR;
 const remaining=BigInt(state.reserveMicroBreaths)+change,reserve=Number(remaining<0n?0n:remaining>BigInt(PLAYER_BREATH_CAPACITY_MICRO)?BigInt(PLAYER_BREATH_CAPACITY_MICRO):remaining),difference=reserve-state.reserveMicroBreaths,day=Number(BigInt(kaiUPulse)/KAI_N_DAY_MICRO);
 const add=(a:number,b:number)=>Math.min(Number.MAX_SAFE_INTEGER,a+b);
 return {...state,reserveMicroBreaths:reserve,spentMicroBreaths:add(state.spentMicroBreaths,Math.max(0,-difference)),restoredMicroBreaths:add(state.restoredMicroBreaths,Math.max(0,difference)),spentTodayMicroBreaths:add(day===state.day?state.spentTodayMicroBreaths:0,Math.max(0,-difference)),lastKaiUPulse:kaiUPulse,day,mode,timeRemainder:(remaining<0n||remaining>BigInt(PLAYER_BREATH_CAPACITY_MICRO))?'0':String(numerator%DENOMINATOR)};
}
export function spendPlayerBreaths(state:PlayerBreaths,breaths:number):PlayerBreaths{if(!isPlayerBreaths(state)||!Number.isFinite(breaths)||breaths<0||breaths>1_000_000)throw Error('player_breath_cost_invalid');const cost=Math.min(state.reserveMicroBreaths,Math.round(breaths*1_000_000));if(cost===0)return state;return {...state,reserveMicroBreaths:state.reserveMicroBreaths-cost,spentMicroBreaths:Math.min(Number.MAX_SAFE_INTEGER,state.spentMicroBreaths+cost),spentTodayMicroBreaths:Math.min(Number.MAX_SAFE_INTEGER,state.spentTodayMicroBreaths+cost),mode:state.mode==='camp'||state.mode==='bed'?'active':state.mode};}
export function playerBreathEnergy(state:PlayerBreaths){return state.reserveMicroBreaths/PLAYER_BREATH_CAPACITY_MICRO*100;}
export function playerBreathReadout(state:PlayerBreaths,kaiUPulse=state.lastKaiUPulse){if(!validKai(kaiUPulse))throw Error('player_breath_time_invalid');const kai=BigInt(kaiUPulse),elapsed=Number(kai%KAI_N_DAY_MICRO*BigInt(PLAYER_BREATHS_PER_DAY)/KAI_N_DAY_MICRO);return {breathsPerDay:PLAYER_BREATHS_PER_DAY,elapsedBreaths:elapsed,remainingDayBreaths:PLAYER_BREATHS_PER_DAY-elapsed,reserveBreaths:Math.floor(state.reserveMicroBreaths/1_000_000),spentTodayBreaths:Math.floor(state.spentTodayMicroBreaths/1_000_000),energyPercent:playerBreathEnergy(state),day:Number(kai/KAI_N_DAY_MICRO),mode:state.mode};}
